[request]
approved = 2021-09-01T17:17:52.625Z
completed = 2021-10-14T10:43:24.537Z
nsfw = false

body_english = """
こよみんさん、こんにちは！

またお世話になります！

プリヤの映画のお祝いにイリヤちゃんと美遊ちゃんを描いて頂きたいです！

映画のマリンルックver.のタペストリーはすごく可愛いなので、その服装で描くと嬉しいです！

詳細はお任せします。

お祝いなので楽しく描いてください！

いつもありがとうございます！
"""

body_japanese = """
こよみんさん、こんにちは！

またお世話になります！

プリヤの映画のお祝いにイリヤちゃんと美遊ちゃんを描いて頂きたいです！

映画のマリンルックver.のタペストリーはすごく可愛いなので、その服装で描くと嬉しいです！

詳細はお任せします。

お祝いなので楽しく描いてください！

いつもありがとうございます！
"""

boost_english = """
わー！すごく似合うよ二人とも！
こよみんさんのプリヤの絵はいつもすごく素敵で可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく似合うよ二人とも！
こよみんさんのプリヤの絵はいつもすごく素敵で可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "こよみん"
handle = "coyomin_s"
twitter = "coyomin_s"
skeb = "coyomin_s"
pixiv = 61788