[request]
approved = 2021-10-07T13:37:14.146Z
completed = 2021-10-15T05:42:37.719Z
nsfw = false

body_english = """
如月二皓さん、はじめまして！

アピールしてありがとうございます！

「小女ラムネ」の「足立甜花」を描いて頂きたいです！

沢山の詳細がないのですみませんでしたけど、アイドルっぽいの甜花を描いてくれたら嬉しいです！

ありがとうございます！
"""

body_japanese = """
如月二皓さん、はじめまして！

アピールしてありがとうございます！

「小女ラムネ」の「足立甜花」を描いて頂きたいです！

沢山の詳細がないのですみませんでしたけど、アイドルっぽいの甜花を描いてくれたら嬉しいです！

ありがとうございます！
"""

boost_english = """
わー！とても可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！とても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "如月二皓"
handle = "ksrgniho"
twitter = "ksrgniho"
skeb = "ksrgniho"
