[request]
approved = 2021-09-24T21:43:31.265Z
completed = 2021-09-29T13:03:39.320Z
nsfw = true

body_english = """
菓色さん、はじめまして！

アピールしてありがとうございます！

よかったら、菓色さんが千恵ちゃん推しで、私は甜花ちゃん推しので、「小女ラムネ」の３人ともを描いて頂きたいです。

詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
菓色さん、はじめまして！

アピールしてありがとうございます！

よかったら、菓色さんが千恵ちゃん推しで、私は甜花ちゃん推しので、「小女ラムネ」の３人ともを描いて頂きたいです。

詳細などお任せします！

ありがとうございます！
"""

boost_english = """
3人ともはめっちゃエロくて可愛い！
ありがとうございます！
"""

boost_japanese = """
3人ともはめっちゃエロくて可愛い！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "菓色（かしき）@Skeb"
handle = "kashiki_main"
twitter = "kashiki_main"
skeb = "kashiki_main"
pixiv = 26805741