[request]
approved = 2021-07-06T00:05:59.057Z
completed = 2021-07-11T16:45:57.424Z
nsfw = true

body_english = """
根所みつさん、はじめまして！

アピールしてありがとうございます！

小女ラムネがプレイした人を見つけるのがいつも嬉しいです！

「小女ラムネ」の「足立甜花」を描いてお願いしたいんです！

田舎の空気感はたっぷりあるのエロシーンが描いてたら嬉しいです！

シーンの詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
根所みつさん、はじめまして！

アピールしてありがとうございます！

小女ラムネがプレイした人を見つけるのがいつも嬉しいです！

「小女ラムネ」の「足立甜花」を描いてお願いしたいんです！

田舎の空気感はたっぷりあるのエロシーンが描いてたら嬉しいです！

シーンの詳細などお任せします！

ありがとうございます！
"""

boost_english = """
わー！甜花ちゃんすごくエロい！
沢山のスイーツを買いますので、沢山のエッチ事をしてください！
ありがとうございます！
"""

boost_japanese = """
わー！甜花ちゃんすごくエロい！
沢山のスイーツを買いますので、沢山のエッチ事をしてください！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "根所みつ"
handle = "takasinanana"
twitter = "takasinanana"
skeb = "takasinanana"
pixiv = 54258761