[request]
approved = 2021-05-10T15:09:40.046Z
completed = 2021-07-08T08:56:56.027Z
nsfw = true

body_english = """
７２５さん、はじめまして！

アピールしてありがとうございます！

もしよければ、「小女ラムネ」の「足立甜花」を描いてお願いしたいんです。

あまりテーマが考えないので、テーマと詳細などお任せします！

NSFWはONだけど、エッチな絵を描くかどうかお任せします。

ありがとうございます！
"""

body_japanese = """
７２５さん、はじめまして！

アピールしてありがとうございます！

もしよければ、「小女ラムネ」の「足立甜花」を描いてお願いしたいんです。

あまりテーマが考えないので、テーマと詳細などお任せします！

NSFWはONだけど、エッチな絵を描くかどうかお任せします。

ありがとうございます！
"""

boost_english = """
わー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "７２５@skeb募集中"
handle = "y725natsu"
twitter = "y725natsu"
skeb = "y725natsu"
