[request]
approved = 2021-12-16T22:22:58.714Z
completed = 2021-12-17T18:09:46.870Z
nsfw = true

body_english = """
Hexさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

もしよかったら、「小女ラムネ」の「足立甜花」を描いて頂きたいです！

詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
Hexさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

もしよかったら、「小女ラムネ」の「足立甜花」を描いて頂きたいです！

詳細などお任せします！

ありがとうございます！
"""

boost_english = """
うぉー！すごくエロくて可愛いです！
甜花ちゃんの体をこんなに興奮しちゃって早速入れたい！
MBと裸差分も感謝しています！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごくエロくて可愛いです！
甜花ちゃんの体をこんなに興奮しちゃって早速入れたい！
MBと裸差分も感謝しています！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "hex🔞skeb募集中"
handle = "Hex114514"
twitter = "HexVsuko"
skeb = "Hex114514"
pixiv = 63138977