[request]
approved = 2021-08-05T21:36:09.102Z
completed = 2021-08-28T18:54:52.137Z
nsfw = true

body_english = """
うろさん、はじめまして！

アピールしてありがとうございます！

「小女ラムネ」の「足立甜花」を描いてお願いしたいんです！

詳細など全部お任せします！

ありがとうございます！
"""

body_japanese = """
うろさん、はじめまして！

アピールしてありがとうございます！

「小女ラムネ」の「足立甜花」を描いてお願いしたいんです！

詳細など全部お任せします！

ありがとうございます！
"""

boost_english = """
うぉー！すごくエロく可愛いです！
さすがにお外でこんなのエロいパンツ着てる甜花ちゃんは最高です！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごくエロく可愛いです！
さすがにお外でこんなのエロいパンツ着てる甜花ちゃんは最高です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "うろ"
handle = "urokabane"
twitter = "urokabane"
skeb = "urokabane"
pixiv = 71405254