[request]
approved = 2021-08-25T04:15:52.846Z
completed = 2021-08-30T10:58:39.676Z
nsfw = false

body_english = """
夏ちゃん、こんにちは！

今年のお誕生日プレゼントにはまたイリヤちゃんをリクエストしたいです！

今回はイリヤちゃんのウエディングビキニ衣装です！イリヤちゃんがビキニに自分をプレゼントしてくれます！

イリヤちゃんを楽しく描いてください！

いつもありがとうございます！
"""

body_japanese = """
夏ちゃん、こんにちは！

今年のお誕生日プレゼントにはまたイリヤちゃんをリクエストしたいです！

今回はイリヤちゃんのウエディングビキニ衣装です！イリヤちゃんがビキニに自分をプレゼントしてくれます！

イリヤちゃんを楽しく描いてください！

いつもありがとうございます！
"""

boost_english = """
わー！すごくきれいです！
ウエディングビキニはやっぱり最高です！
ありがとうございます！
"""

boost_japanese = """
わー！すごくきれいです！
ウエディングビキニはやっぱり最高です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "夏"
handle = "sinker8c"
twitter = "sinker8c"
skeb = "sinker8c"
pixiv = 12429243