[request]
approved = 2021-12-19T23:43:16.429Z
completed = 2021-12-20T02:28:43.084Z
nsfw = true

body_english = """
古山造さん、はじめまして！

アピールしてありがとうございます！こんなすごい神絵師からアピールを貰えるのはすごく嬉しいです！

古山造さんのエロい絵のが大好きなので、もしよかったら、「小女ラムネ」の「足立甜花」を描いて頂きたいです！

どのような甜花ちゃんを描くのか気になるので、詳細など全部お任せします！

ありがとうございます！
"""

body_japanese = """
古山造さん、はじめまして！

アピールしてありがとうございます！こんなすごい神絵師からアピールを貰えるのはすごく嬉しいです！

古山造さんのエロい絵のが大好きなので、もしよかったら、「小女ラムネ」の「足立甜花」を描いて頂きたいです！

どのような甜花ちゃんを描くのか気になるので、詳細など全部お任せします！

ありがとうございます！
"""

boost_english = """
わー！すごい早いです！
すごくエロくて可愛いです！
服を脱いでる甜花ちゃんは最高です！
乳首を見せる差分の感謝しています！
ありがとうございます！
"""

boost_japanese = """
わー！すごい早いです！
すごくエロくて可愛いです！
服を脱いでる甜花ちゃんは最高です！
乳首を見せる差分の感謝しています！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "古山　造"
handle = "tshangen"
twitter = "tshangen"
skeb = "tshangen"
pixiv = 42423091