[request]
approved = 2021-10-24T22:28:22.423Z
completed = 2021-11-29T12:20:09.741Z
nsfw = false

body_english = """
𝕔𝕙𝕣𝕠𝕟𝕚𝕔𝕒さん、こんにちは！

Fateシリーズのイリヤちゃんを描いて頂きたいです。

詳細など全部お任せします！

ありがとうございます！
"""

body_japanese = """
𝕔𝕙𝕣𝕠𝕟𝕚𝕔𝕒さん、こんにちは！

Fateシリーズのイリヤちゃんを描いて頂きたいです。

詳細など全部お任せします！

ありがとうございます！
"""

boost_english = """
わー！と～ても可愛いです！
いつもありがとうございます！
"""

boost_japanese = """
わー！と～ても可愛いです！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "𝕔𝕙𝕣𝕠𝕟𝕚𝕔𝕒"
handle = "chr0nica"
twitter = "chr0nica"
skeb = "chr0nica"
