[request]
approved = 2021-09-28T00:57:42.296Z
completed = 2022-01-07T22:15:31.472Z
nsfw = true

body_english = """
ヌケルさん、こんにちは！

またお世話になります！

前回の甜花ちゃんはとてもエロくて可愛かったので、よかったらまた「小女ラムネ」の「足立甜花」を描いて頂きたいです！

ヌケルさんのエロいじめのイラストがすごく大好きです！特に「1いいねにつき0.1mmアナルを拡張される女の子」と「鳴乃皐月のメス豚配信」は最高だった！

それなので、また「アイドルになるために何でもします」のリクエストです！

今回は前回よりもっとエロいじめとおしおきのテーマです！

詳細など全部お任せします！

首絞めでもリョナでも何でも大丈夫なので、自由に描いてください！

ありがとうございます！
"""

body_japanese = """
ヌケルさん、こんにちは！

またお世話になります！

前回の甜花ちゃんはとてもエロくて可愛かったので、よかったらまた「小女ラムネ」の「足立甜花」を描いて頂きたいです！

ヌケルさんのエロいじめのイラストがすごく大好きです！特に「1いいねにつき0.1mmアナルを拡張される女の子」と「鳴乃皐月のメス豚配信」は最高だった！

それなので、また「アイドルになるために何でもします」のリクエストです！

今回は前回よりもっとエロいじめとおしおきのテーマです！

詳細など全部お任せします！

首絞めでもリョナでも何でも大丈夫なので、自由に描いてください！

ありがとうございます！
"""

boost_english = """
わー！とてもエロい！
甜花ちゃんのIVデビュ！
いつもありがとうございます！
"""

boost_japanese = """
わー！とてもエロい！
甜花ちゃんのIVデビュ！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ヌケル(さん) @C99新刊通販・DL販売中"
handle = "kawaisonukeru"
twitter = "nukerusan"
skeb = "kawaisonukeru"
pixiv = 58172120