[request]
approved = 2022-03-27T06:20:51.595Z
completed = 2022-05-05T09:54:57.733Z
nsfw = false

body_english = """
クロニカさん、こんにちは！

またお世話になります！

今回はヨスガノソラの穹ちゃんを描いて頂きたいです。

詳細など全部お任せします！

いつもありがとうございます！
"""

body_japanese = """
クロニカさん、こんにちは！

またお世話になります！

今回はヨスガノソラの穹ちゃんを描いて頂きたいです。

詳細など全部お任せします！

いつもありがとうございます！
"""

boost_english = """
わぁ！穹ちゃんは素敵ですね！
とても可愛いです！
ありがとうございます！
"""

boost_japanese = """
わぁ！穹ちゃんは素敵ですね！
とても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "𝕔𝕙𝕣𝕠𝕟𝕚𝕔𝕒"
handle = "chr0nica"
twitter = "chr0nica"
skeb = "chr0nica"
