[request]
approved = 2022-01-04T15:53:22.723Z
completed = 2022-02-01T10:22:54.649Z
nsfw = true

body_english = """
ましまろさん、こんにちは！

またお世話になります！

今回はフータオちゃんを描いて頂きたいです。

大体の詳細などお任せしますけど、エロい絵のリクエストなので自由にすごくエロくて可愛いフータオちゃんを描いて下さい！

ありがとうございます！
"""

body_japanese = """
ましまろさん、こんにちは！

またお世話になります！

今回はフータオちゃんを描いて頂きたいです。

大体の詳細などお任せしますけど、エロい絵のリクエストなので自由にすごくエロくて可愛いフータオちゃんを描いて下さい！

ありがとうございます！
"""

boost_english = """
いつものようにすごい！
ありがとうございます！
"""

boost_japanese = """
いつものようにすごい！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ましまろ"
handle = "msmrdaaaaa"
twitter = "msmrdaaaaa"
skeb = "msmrdaaaaa"
pixiv = 15867481