[request]
approved = 2021-12-06T07:15:15.397Z
completed = 2022-04-02T14:40:08.493Z
nsfw = true

body_english = """
山家大右衛門さん、こんにちは！

またお世話になります！

山家大右衛門さんのエロい絵がめっちゃ大好きなので、今回も「小女ラムネ」の「足立甜花」を描いて頂きたいです！

今回はどんなフェチやシチュでも良いので、よかったら詳細はお任せします。

いつもありがとうございます！
"""

body_japanese = """
山家大右衛門さん、こんにちは！

またお世話になります！

山家大右衛門さんのエロい絵がめっちゃ大好きなので、今回も「小女ラムネ」の「足立甜花」を描いて頂きたいです！

今回はどんなフェチやシチュでも良いので、よかったら詳細はお任せします。

いつもありがとうございます！
"""

boost_english = """
めっちゃエロいです！
いつもありがとうございます！
"""

boost_japanese = """
めっちゃエロいです！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "山家大右衛門🔞C99新刊🐯🍈委託中"
handle = "oowemon_yamaya"
twitter = "oowemon_yamaya"
skeb = "oowemon_yamaya"
