[request]
approved = 2022-05-29T22:55:25.449Z
completed = 2022-06-09T14:40:23.644Z
nsfw = true

body_english = """
神門さん、こんにちは！

またお世話になります！

今回はプリヤの三姉妹を描いて頂きたいです！

大体のテーマは3人のウェディングビキニ姿ですけど、他の詳細など全部お任せします！

いつもありがとうございます！
"""

body_japanese = """
神門さん、こんにちは！

またお世話になります！

今回はプリヤの三姉妹を描いて頂きたいです！

大体のテーマは3人のウェディングビキニ姿ですけど、他の詳細など全部お任せします！

いつもありがとうございます！
"""

boost_english = """
いつものようにとてもすごいです！
本当にありがとうございます！
"""

boost_japanese = """
いつものようにとてもすごいです！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "神門（かみもん）"
handle = "SchwarzKap"
twitter = "SchwarzKap"
skeb = "SchwarzKap"
pixiv = 1437365