[request]
approved = 2022-04-10T22:49:51.038Z
completed = 2022-04-14T19:00:10.494Z
nsfw = false

body_english = """
えりんさん、はじめまして！

アピールしてありがとうございます！

足立甜花ちゃんのアピールを貰うのはちょっと珍しいのですごく嬉しいので、甜花ちゃんを描いて頂きたいです！

詳細など全部お任せします！

ありがとうございます！
"""

body_japanese = """
えりんさん、はじめまして！

アピールしてありがとうございます！

足立甜花ちゃんのアピールを貰うのはちょっと珍しいのですごく嬉しいので、甜花ちゃんを描いて頂きたいです！

詳細など全部お任せします！

ありがとうございます！
"""

boost_english = """
わっ！めっちゃ可愛いです！
目はすごく綺麗で、とても素敵な笑顔です！
パンチラまで見えちゃう！
ありがとうございます！
"""

boost_japanese = """
わっ！めっちゃ可愛いです！
目はすごく綺麗で、とても素敵な笑顔です！
パンチラまで見えちゃう！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "えりん⚡3ヶ月上達法実践中⚡"
handle = "erin_oekaki0803"
twitter = "erin_oekaki0803"
skeb = "erin_oekaki0803"
pixiv = 823107