[request]
approved = 2022-01-25T16:47:25.396Z
completed = 2022-02-13T06:18:07.882Z
nsfw = true

body_english = """
ごりらっくまさん、こんにちは！

またを世話になります！

今回はごりらっくまさんの自己キャラを描いて頂きたいです。

大体のテーマはおもらしだけど、詳細など全部お任せします！

いつも本当にありがとうございます！
"""

body_japanese = """
ごりらっくまさん、こんにちは！

またを世話になります！

今回はごりらっくまさんの自己キャラを描いて頂きたいです。

大体のテーマはおもらしだけど、詳細など全部お任せします！

いつも本当にありがとうございます！
"""

boost_english = """
わー！とてもエロくて可愛いです！
ごりらっくまちゃんは素敵なペットになっちゃった！
水をいっぱい飲んで、ご主人様の目の前におもらししてくれてえらいです！
バレンタインのおまけもめっちゃありがたいです！
いつもありがとうございます！
"""

boost_japanese = """
わー！とてもエロくて可愛いです！
ごりらっくまちゃんは素敵なペットになっちゃった！
水をいっぱい飲んで、ご主人様の目の前におもらししてくれてえらいです！
バレンタインのおまけもめっちゃありがたいです！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ごりらっくま🔞skeb受付中"
handle = "gorillakkuman"
twitter = "gorillakkuman"
skeb = "gorillakkuman"
pixiv = 64023161