base_url = "https://commission.tenka.dev"

title = "Tenka Commissions"
description = "A showcase of all the illustrations of Shoujo Ramune's Tenka Adachi that I've commissioned."

default_language = "en"

# generate_rss = true
build_search_index = false

compile_sass = true
highlight_code = false

languages = [
  { code = "ja" },
]

[translations]

[translations.en]
title = "Tenka Commissions"
about = "About"
stats = "Stats"
appeals = "Appeals"
description = "A showcase of all the illustrations of Shoujo Ramune's Tenka Adachi that I've commissioned."
date_format = "%Y-%m-%d"
days = " days"

accepted = "Accepted"
completed = "Completed"
duration = "Duration"
twitter = "Twitter"
skeb = "Skeb"
pixiv = "Pixiv ID"
artistsnclients = "Artists&Clients"
fiverr = "Fiverr"

request = "Request"

[translations.ja]
title = "甜花ちゃんのコミッション"
about = "サイトについて知る"
stats = " スタッツ"
description = "俺のリクエストした「小女ラムネ」の「足立甜花」のイラスト。"
date_format = "%Y年%m月%d日"
days = "日間"

accepted = "承認日"
completed = "納品日"
duration = "期間"
twitter = "ツイッター"
skeb = "Skeb"
pixiv = "pixiv"
artistsnclients = "Artists&Clients"
fiverr = "Fiverr"

request = "リクエスト"