base_url = "https://commission.tenka.dev"

title = "Commissions"
description = "A showcase of all the illustrations that I've commissioned."

default_language = "en"

# generate_rss = true
build_search_index = false

compile_sass = true
highlight_code = false

[translations]
title = "Commissions"
home = "Home"
about = "About"
stats = "Stats"
banners = "Banners"
description = "A showcase of all the illustrations that I've commissioned."
date_format = "%Y-%m-%d"
days = " days"
hours = " hours"
seemore = "See More"

delivery = "Delivery"
fastest = "Fastest"
average = "Average"
slowest = "Slowest"
totals = "Totals"
requests = "Requests"
date = "Date"
count = "Count"

accepted = "Accepted"
completed = "Completed"
duration = "Duration"
twitter = "Twitter"
skeb = "Skeb"
pixiv = "Pixiv ID"
artistsnclients = "Artists&Clients"
fiverr = "Fiverr"

request = "Request"


[languages.ja.translations]

title = "コミッション"
home = "ホーム"
about = "サイトについて知る"
stats = " スタッツ"
banners = " ヘッダー"
description = "俺のリクエストしたのイラスト。"
date_format = "%Y年%m月%d日"
days = "日間"
hours = "時間"
seemore = "もっと"

delivery = "完了時間"
fastest = "一番速い"
average = "平均"
slowest = "一番遅い"
totals = "総数"
requests = "リクエスト"
date = "時間軸"
count = "総数"

accepted = "承認日"
completed = "納品日"
duration = "期間"
twitter = "ツイッター"
skeb = "Skeb"
pixiv = "pixiv"
artistsnclients = "Artists&Clients"
fiverr = "Fiverr"

request = "リクエスト"