[request]
approved = 2021-06-24T06:30:44.568Z
completed = 2021-07-19T04:10:30.213Z
nsfw = false

body_english = """
黒猫かしすさん、はじめまして！

アピールしてありがとうございます！

すごく優しいメッセージを貰えて嬉しいです！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

大体テーマはすごくツンデレっぽいのシーンです。

恥ずかしいことを思わずに言ったので、エマちゃんが真っ赤で怒られちゃった。

他の詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
黒猫かしすさん、はじめまして！

アピールしてありがとうございます！

すごく優しいメッセージを貰えて嬉しいです！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

大体テーマはすごくツンデレっぽいのシーンです。

恥ずかしいことを思わずに言ったので、エマちゃんが真っ赤で怒られちゃった。

他の詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！めっちゃツンツンのエマちゃんだ！
すごくエマちゃんらしい！とても可愛いです！
ありがとうございます！
"""

boost_japanese = """
うぉー！めっちゃツンツンのエマちゃんだ！
すごくエマちゃんらしい！とても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ꫛꫀꪝ✧‧˚かしす"
handle = "kashisu_9625"
twitter = "kashisu_9625"
skeb = "kashisu_9625"
pixiv = 10379543