[request]
approved = 2021-07-23T11:50:11.772Z
completed = 2021-08-17T16:31:38.920Z
nsfw = false

body_english = """
ユイザキカズヤさん、はじめまして！

カナダからの大ファンです！ココアホリックの同人誌と繭ちゃんがすごく大好きです！

もしよかったら、私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです！

下のURLでは三面図を載せているツイートです。

どんなエマちゃんを描くのか気になるから、詳細などは全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ユイザキカズヤさん、はじめまして！

カナダからの大ファンです！ココアホリックの同人誌と繭ちゃんがすごく大好きです！

もしよかったら、私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです！

下のURLでは三面図を載せているツイートです。

どんなエマちゃんを描くのか気になるから、詳細などは全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！すごくきれいです！
ユイザキカズヤさんが描いた目はずっと大好きです！
本当にありがとうございます！
"""

boost_japanese = """
うぉー！すごくきれいです！
ユイザキカズヤさんが描いた目はずっと大好きです！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ユイザキカズヤ🌱GW新刊発売中"
handle = "k_yuizaki"
twitter = "k_yuizaki"
skeb = "k_yuizaki"
