[request]
approved = 2021-12-01T02:49:49.680Z
completed = 2021-12-15T13:58:08.415Z
nsfw = false

body_english = """
なのはさん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです！

クリスマスキャンペーンのツイートを見たので、クリスマスっぽいのエマちゃんを描いてくれたら嬉しいです！

他の詳細などお任せします。

いつもありがとうございます！
"""

body_japanese = """
なのはさん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです！

クリスマスキャンペーンのツイートを見たので、クリスマスっぽいのエマちゃんを描いてくれたら嬉しいです！

他の詳細などお任せします。

いつもありがとうございます！
"""

boost_english = """
わー！エマちゃんからのクリスマスプレゼント！！
嬉しい過ぎます！
今回の絵もすごく可愛いです！
もう一度ありがとうございます！
メリークリスマス！
"""

boost_japanese = """
わー！エマちゃんからのクリスマスプレゼント！！
嬉しい過ぎます！
今回の絵もすごく可愛いです！
もう一度ありがとうございます！
メリークリスマス！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "なのは@Skeb作業中"
handle = "nanoha_wani"
twitter = "nanoha_wani"
skeb = "nanoha_wani"
pixiv = 62868404