[request]
approved = 2021-11-02T15:12:18.711Z
completed = 2021-12-31T14:07:16.879Z
nsfw = false

body_english = """
ぴぴぴさん、こんにちは！

またお世話になります！

今回は私のエマちゃんとぴぴぴさんのホス狂ちゃんのクロスオーバー絵を描いて頂きたいです！

詳細など全部お任せします。

いつもありがとうございます！
"""

body_japanese = """
ぴぴぴさん、こんにちは！

またお世話になります！

今回は私のエマちゃんとぴぴぴさんのホス狂ちゃんのクロスオーバー絵を描いて頂きたいです！

詳細など全部お任せします。

いつもありがとうございます！
"""

boost_english = """
ホス狂ちゃんとエマちゃんは可愛すぎ！
本当にありがとうございます！
ずっと大切にします！
"""

boost_japanese = """
ホス狂ちゃんとエマちゃんは可愛すぎ！
本当にありがとうございます！
ずっと大切にします！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ぴぴぴ"
handle = "pipipipikyomu"
twitter = "pipipipikyomu"
skeb = "pipipipikyomu"
