[request]
approved = 2021-09-05T01:49:48.825Z
completed = 2021-10-07T01:42:14.515Z
nsfw = false

body_english = """
ましまろさん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです。

もうすぐハロウィーンなので、エマちゃんが仮装したいです！ハロウィーンの衣装を描いてくれると嬉しいです！

衣装と他の詳細など全部お任せします！

ありがとうございます！
"""

body_japanese = """
ましまろさん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです。

もうすぐハロウィーンなので、エマちゃんが仮装したいです！ハロウィーンの衣装を描いてくれると嬉しいです！

衣装と他の詳細など全部お任せします！

ありがとうございます！
"""

boost_english = """
うわー！すごいです！
両の衣装はとても可愛いです！
流石にメスガキは最高！
ありがとうございます！
"""

boost_japanese = """
うわー！すごいです！
両の衣装はとても可愛いです！
流石にメスガキは最高！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ましまろ@skeb一時停止"
handle = "msmrdaaaaa"
twitter = "msmrdaaaaa"
skeb = "msmrdaaaaa"
pixiv = 15867481