[request]
approved = 2021-11-24T11:37:48.977Z
completed = 2021-12-01T17:14:06.124Z
nsfw = true

body_english = """
神門さん、こんにちは！

またお世話になります！

突然にエマちゃんのFAを貰えてすごく嬉しくなったので、またエマちゃんを描いて頂きたいです！

今回はエマちゃんの私服を描いてくれたら嬉しいです！

下のURLでは私服の参考の写真を載せているツイートです！

ポーズと他の詳細などお任せします！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

body_japanese = """
神門さん、こんにちは！

またお世話になります！

突然にエマちゃんのFAを貰えてすごく嬉しくなったので、またエマちゃんを描いて頂きたいです！

今回はエマちゃんの私服を描いてくれたら嬉しいです！

下のURLでは私服の参考の写真を載せているツイートです！

ポーズと他の詳細などお任せします！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

boost_english = """
わー！すごく綺麗です！
いつもありがとうございます！
"""

boost_japanese = """
わー！すごく綺麗です！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "神門（かみもん）＠Skeb募集中"
handle = "SchwarzKap"
twitter = "SchwarzKap"
skeb = "SchwarzKap"
pixiv = 1437365