[request]
approved = 2021-12-08T17:04:14.675Z
completed = 2021-12-15T23:24:18.331Z
nsfw = true

body_english = """
らみちゅんさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

あまり詳細がなくてすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいので、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
らみちゅんさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

あまり詳細がなくてすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいので、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！エマちゃんの部屋着！
めっちゃくちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！エマちゃんの部屋着！
めっちゃくちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "らみちゅん！skeb募集中"
handle = "Lamy_chun"
twitter = "Lamy_chun"
skeb = "Lamy_chun"
pixiv = 59462809