[request]
approved = 2021-07-08T00:21:30.978Z
completed = 2021-07-13T10:40:05.363Z
nsfw = false

body_english = """
☆さん、こんにちは！

またお世話にになりました！

前回のイリヤちゃんと甜花ちゃんの絵はすごく可愛かったので、私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

特にテーマがないので、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
☆さん、こんにちは！

またお世話にになりました！

前回のイリヤちゃんと甜花ちゃんの絵はすごく可愛かったので、私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

特にテーマがないので、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うわー！いつも☆さんの絵はめっちゃきれいです！
顔と水着はすごく大好きです！
ありがとうございます！
"""

boost_japanese = """
うわー！いつも☆さんの絵はめっちゃきれいです！
顔と水着はすごく大好きです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "☆"
handle = "rst_hoshinono"
twitter = "rst_hoshinono"
skeb = "rst_hoshinono"
