[request]
approved = 2021-07-05T06:25:34.055Z
completed = 2021-07-15T12:51:24.858Z
nsfw = false

body_english = """
イチノセ奏さん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

エマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
イチノセ奏さん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

エマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
あー！すごい！
ゲームしてるエマちゃんはめっちゃ可愛い！
ありがとうございます！
"""

boost_japanese = """
あー！すごい！
ゲームしてるエマちゃんはめっちゃ可愛い！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "イチノセ奏"
handle = "kanade_cocotte"
twitter = "kanade_cocotte"
skeb = "kanade_cocotte"
pixiv = 366714