[request]
approved = 2021-10-08T21:44:58.511Z
completed = 2021-10-17T21:46:13.277Z
nsfw = false

body_english = """
chessさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

あまり詳細がなくてすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
chessさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

あまり詳細がなくてすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！すごい！
水が服にしみ込んで、ブラは丸見える！
すごく可愛いです！！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごい！
水が服にしみ込んで、ブラは丸見える！
すごく可愛いです！！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "chess"
handle = "chess425"
twitter = "chess425"
skeb = "chess425"
