[request]
approved = 2021-09-10T02:08:29.988Z
completed = 2021-09-11T10:48:45.931Z
nsfw = false

body_english = """
陽崎杜萌子さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
陽崎杜萌子さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！
"""

boost_english = """
わー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "陽崎杜萌子"
handle = "hizakitomoko"
twitter = "hizakitomoko"
skeb = "hizakitomoko"
pixiv = 462484