[request]
approved = 2021-10-21T13:09:05.311Z
completed = 2021-10-24T15:11:05.464Z
nsfw = false

body_english = """
ᴍᴇᴄʜɪʀᴜさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ᴍᴇᴄʜɪʀᴜさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ᴍᴇᴄʜɪʀᴜ"
handle = "mechirudesu"
twitter = "mechirudesu"
skeb = "mechirudesu"
pixiv = 29435064