[request]
approved = 2021-09-08T13:51:51.020Z
completed = 2021-09-15T09:34:47.048Z
nsfw = false

body_english = """
蒼ウサギさん、こんにちは！

またお世話になります！

よかったら、今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

最近はエマちゃんが新しい私服をデザインして貰いましたので、その私服を描いてくれると嬉しいです！

下のURLでは衣装の参考ツイートです！

そのスレッドでもエマちゃんの三面図を載せているツイートがあります！

蒼ウサギさんのイラストはいつもすごく可愛いなので、詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

body_japanese = """
蒼ウサギさん、こんにちは！

またお世話になります！

よかったら、今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

最近はエマちゃんが新しい私服をデザインして貰いましたので、その私服を描いてくれると嬉しいです！

下のURLでは衣装の参考ツイートです！

そのスレッドでもエマちゃんの三面図を載せているツイートがあります！

蒼ウサギさんのイラストはいつもすごく可愛いなので、詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

boost_english = """
あぁ、めっちゃ可愛いです！
ウサギさんのイラストはいつも可愛いすぎ！
ありがとうございます！
"""

boost_japanese = """
あぁ、めっちゃ可愛いです！
ウサギさんのイラストはいつも可愛いすぎ！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "蒼ウサギ♂@skeb募集中"
handle = "AoUSA0328"
twitter = "AoUSA0328"
skeb = "AoUSA0328"
pixiv = 19095613