[request]
approved = 2021-11-10T00:10:38.150Z
completed = 2021-11-15T09:24:14.878Z
nsfw = false

body_english = """
安蔵くんこさん、はじめまして！

アピールしてありがとうございます！

リクエスト手数料無料キャンペーンの終わる前にリクエストしなくてすみませんでした！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
安蔵くんこさん、はじめまして！

アピールしてありがとうございます！

リクエスト手数料無料キャンペーンの終わる前にリクエストしなくてすみませんでした！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！ツンデレ幼馴染からのクッキー！すっごく食べたい！
エマちゃんの性格通り！とても可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！ツンデレ幼馴染からのクッキー！すっごく食べたい！
エマちゃんの性格通り！とても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "安蔵くんこ"
handle = "ANZ_KNK"
twitter = "ANZ_KNK"
skeb = "ANZ_KNK"
