[request]
approved = 2021-12-14T12:27:44.705Z
completed = 2021-12-29T08:46:16.286Z
nsfw = false

body_english = """
橋弧のをとさん、こんにちは！

またお世話になります！前回の甜花ちゃんのイラストはとても可愛かったです！

もしよかったら、数月前に自分のオリジナルキャラクターをデザインしてもらったので、今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので、今回は健全のリクエストだけど、どのようなエマちゃんを描くのか気になるから、詳細など全部お任せします！

今回もまた白髪か銀髪キャラじゃなくてすみませんでした！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
橋弧のをとさん、こんにちは！

またお世話になります！前回の甜花ちゃんのイラストはとても可愛かったです！

もしよかったら、数月前に自分のオリジナルキャラクターをデザインしてもらったので、今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので、今回は健全のリクエストだけど、どのようなエマちゃんを描くのか気になるから、詳細など全部お任せします！

今回もまた白髪か銀髪キャラじゃなくてすみませんでした！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！とても可愛いです！
パフェもすごく美味しそう！
本当にありがとうございます！
"""

boost_japanese = """
わー！とても可愛いです！
パフェもすごく美味しそう！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "橋弧のをと@お仕事募集中"
handle = "hashicco_note"
twitter = "hashicco_note"
skeb = "hashicco_note"
pixiv = 9451909