[request]
approved = 2021-08-22T16:13:12.014Z
completed = 2021-09-09T10:14:09.379Z
nsfw = false

body_english = """
りつさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
りつさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごい！
すごくきれいです！
さっそく壁紙にします！
ありがとうございます！
"""

boost_japanese = """
わー！すごい！
すごくきれいです！
さっそく壁紙にします！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ritsu"
handle = "Ritsu_i6"
twitter = "Ritsu_i6"
skeb = "Ritsu_i6"
