[request]
approved = 2021-07-04T20:39:19.548Z
completed = 2021-07-06T06:26:35.450Z
nsfw = false

body_english = """
すましぎなつおさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
すましぎなつおさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "すましぎ なつお【絵仕事募集中】"
handle = "zundokko"
twitter = "zundokko"
skeb = "zundokko"
pixiv = 1425585