[request]
approved = 2021-07-14T15:39:05.096Z
completed = 2021-08-08T02:29:48.852Z
nsfw = false

body_english = """
なみHEYさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
なみHEYさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
あー！沢山の猫と遊んでる！
めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
あー！沢山の猫と遊んでる！
めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "なみへー"
handle = "aya_NH"
twitter = "aya_NH"
skeb = "aya_NH"
pixiv = 137107