[request]
approved = 2021-12-05T07:08:35.728Z
completed = 2021-12-30T11:44:10.267Z
nsfw = false

body_english = """
kirinさん、はじめまして！

もしよかったら、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
kirinさん、はじめまして！

もしよかったら、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく綺麗です！
ありがとうございます！
"""

boost_japanese = """
わー！すごく綺麗です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "kirin"
handle = "kirin1023"
twitter = "kirin1023"
skeb = "kirin1023"
