[request]
approved = 2021-09-24T11:23:01.275Z
completed = 2021-10-10T17:45:06.339Z
nsfw = false

body_english = """
ほしさん、こんにちは！

またお世話になります！

前回は普段着バージョンも描いてみたいと言ったので、今回もエマちゃんを描いて頂きたいです。

詳細など全部お任せします。

いつもありがとうございます！
"""

body_japanese = """
ほしさん、こんにちは！

またお世話になります！

前回は普段着バージョンも描いてみたいと言ったので、今回もエマちゃんを描いて頂きたいです。

詳細など全部お任せします。

いつもありがとうございます！
"""

boost_english = """
わー！すごいです！めっちゃめっちゃ可愛い！
エマちゃんの心の中の思いは可愛すぎる！本当にとてもツンツンですね！
過去のラフまで嬉しいです！
いつもありがとうございます！
"""

boost_japanese = """
わー！すごいです！めっちゃめっちゃ可愛い！
エマちゃんの心の中の思いは可愛すぎる！本当にとてもツンツンですね！
過去のラフまで嬉しいです！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "☆"
handle = "rst_hoshinono"
twitter = "rst_hoshinono"
skeb = "rst_hoshinono"
