[request]
approved = 2021-10-07T13:38:11.457Z
completed = 2021-10-07T18:24:47.080Z
nsfw = false

body_english = """
ひよ太郎さん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

そうですね、私も秋冬らしいふわふわ可愛いエマちゃんを見てみたいので、とても可愛いエマちゃんを描いてくれたら嬉しいです！

詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
ひよ太郎さん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

そうですね、私も秋冬らしいふわふわ可愛いエマちゃんを見てみたいので、とても可愛いエマちゃんを描いてくれたら嬉しいです！

詳細などお任せします！

ありがとうございます！
"""

boost_english = """
すごく可愛いです！
この衣装と、冬でも負けない！
ありがとうございます！
"""

boost_japanese = """
すごく可愛いです！
この衣装と、冬でも負けない！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ひよ太郎"
handle = "YOU_0614_"
twitter = "YOU_0614_"
skeb = "YOU_0614_"
