[request]
approved = 2021-09-19T16:01:35.176Z
completed = 2021-09-22T14:04:50.835Z
nsfw = false

body_english = """
725さん、こんにちは！

またお世話になります！

今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

body_japanese = """
725さん、こんにちは！

またお世話になります！

今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

boost_english = """
わー！すごく可愛いです！
エマちゃんの照れ顔は本当に最高ですね！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
エマちゃんの照れ顔は本当に最高ですね！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "７２５/七月二十五日@skeb募集中"
handle = "y725natsu"
twitter = "y725natsu"
skeb = "y725natsu"
