[request]
approved = 2021-10-26T19:04:21.817Z
completed = 2021-11-15T11:11:44.705Z
nsfw = false

body_english = """
陽さん、はじめまして！

アピールしてありがとうございます！

陽さんのFF14キャラはとても可愛いです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがありましたが、下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
陽さん、はじめまして！

アピールしてありがとうございます！

陽さんのFF14キャラはとても可愛いです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがありましたが、下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "陽*.ﾟ"
handle = "spring__fe"
twitter = "spring__fe"
skeb = "spring__fe"
pixiv = 24678441