[request]
approved = 2021-10-09T10:26:22.633Z
completed = 2021-12-06T13:12:38.975Z
nsfw = false

body_english = """
ゆるぽめさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

あまり詳細がなくてすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ゆるぽめさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

あまり詳細がなくてすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！可愛いです！
ドレスもとても可愛い可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！可愛いです！
ドレスもとても可愛い可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ゆるぽめ"
handle = "yume_unonu"
twitter = "yume_unonu"
skeb = "yume_unonu"
