[request]
approved = 2021-08-14T01:05:29.261Z
completed = 2021-08-17T11:07:00.283Z
nsfw = false

body_english = """
壱城ときさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
壱城ときさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！怖がっているエマちゃんです！
袖をつかんでて泣いちゃってるのに、すごく可愛いです！
強がるふりしてるのに、本物のエマちゃんが出た！
ありがとうございます！
"""

boost_japanese = """
わー！怖がっているエマちゃんです！
袖をつかんでて泣いちゃってるのに、すごく可愛いです！
強がるふりしてるのに、本物のエマちゃんが出た！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "壱城とき@お仕事募集中"
handle = "toki0321"
twitter = "toki0321"
skeb = "toki0321"
pixiv = 1498516