[request]
approved = 2021-09-01T03:55:57.870Z
completed = 2021-09-06T19:00:30.516Z
nsfw = false

body_english = """
ゆきのさん、はじめまして！

アピールしてありがとうございます！

こんな優しいメッセージを貰えてすごく嬉しいです！

もちろん、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図を載せているツイートです！

私もエマちゃんの照れ顔がめっちゃくちゃ大好きなので、こんな感じがある絵を描いてくれたら嬉しいです。

沢山の詳細がなくてすみませんです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ゆきのさん、はじめまして！

アピールしてありがとうございます！

こんな優しいメッセージを貰えてすごく嬉しいです！

もちろん、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図を載せているツイートです！

私もエマちゃんの照れ顔がめっちゃくちゃ大好きなので、こんな感じがある絵を描いてくれたら嬉しいです。

沢山の詳細がなくてすみませんです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごい！
猫耳メイドエマちゃんの写真と寝ているエマちゃんの写真！
そして、見ちゃうダメって言っているの照れ顔はめっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごい！
猫耳メイドエマちゃんの写真と寝ているエマちゃんの写真！
そして、見ちゃうダメって言っているの照れ顔はめっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ゆきの@お仕事募集中"
handle = "yukinoo58"
twitter = "yukinoo58"
skeb = "yukinoo58"
pixiv = 116321