[request]
approved = 2021-11-07T02:03:52.613Z
completed = 2021-11-14T00:19:50.679Z
nsfw = false

body_english = """
もゆりさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
もゆりさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！可愛いです！
表情はめっちゃ良いです！
ありがとうございます！
"""

boost_japanese = """
わー！可愛いです！
表情はめっちゃ良いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "もゆり"
handle = "moyunori"
twitter = "moyunori"
skeb = "moyunori"
