[request]
approved = 2021-10-21T15:49:44.991Z
completed = 2021-11-14T12:38:08.800Z
nsfw = false

body_english = """
LiOさん、はじめまして！

アピールしてありがとうございます！

オリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
LiOさん、はじめまして！

アピールしてありがとうございます！

オリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うわー！めっちゃ可愛いです！
マフラーと八重歯がすごく好きです！
ありがとうございます！
"""

boost_japanese = """
うわー！めっちゃ可愛いです！
マフラーと八重歯がすごく好きです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "LiO@お仕事＋skeb募集中"
handle = "lio8644"
twitter = "lio8644"
skeb = "lio8644"
pixiv = 3732275