[request]
approved = 2021-05-31T18:32:25.745Z
completed = 2021-07-28T10:18:24.657Z
nsfw = false

body_english = """
まふゆさん、はじめまして！

カナダからの大ファンです！たくさんイラスト本と他のグッズを買います！

もしよければ、私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
まふゆさん、はじめまして！

カナダからの大ファンです！たくさんイラスト本と他のグッズを買います！

もしよければ、私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
あぁ、すごい！
すごすぎて言葉が来ない！
本当にありがとうございます！
"""

boost_japanese = """
あぁ、すごい！
すごすぎて言葉が来ない！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "まふゆ👻"
handle = "1kurusk"
twitter = "1kurusk"
skeb = "1kurusk"
pixiv = 5229572