[request]
approved = 2021-06-06T00:23:38.420Z
completed = 2021-08-03T15:03:10.317Z
nsfw = false

body_english = """
はちばいとさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

エマちゃんを描いてお願いしたいんです。

詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
はちばいとさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

エマちゃんを描いてお願いしたいんです。

詳細などお任せします！

ありがとうございます！
"""

boost_english = """
わー！めっちゃくちゃ可愛いです！
ちょっと不安な表現と赤くなった顔のは最高です！
背景もすごくきれいです！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃくちゃ可愛いです！
ちょっと不安な表現と赤くなった顔のは最高です！
背景もすごくきれいです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "はちばいと ミホノブルボン描いた"
handle = "8bite_UoU"
twitter = "8bite_UoU"
skeb = "8bite_UoU"
pixiv = 31570727