[request]
approved = 2021-05-27T15:11:57.538Z
completed = 2021-07-16T23:55:35.433Z
nsfw = false

body_english = """
あまねさん、こんにちは！

今回もお世話になります。

私のオリジナルキャラクター、エマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
あまねさん、こんにちは！

今回もお世話になります。

私のオリジナルキャラクター、エマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！めっちゃ可愛いです！
目が好き！髪が好き！太ももが好き！唇まで可愛い！
完全に真っ赤の顔でシャツをつかまえてるエマちゃんは最高です！
やばっ、可愛すぎてたまらん！
ありがとうございます！
"""

boost_japanese = """
うぉー！めっちゃ可愛いです！
目が好き！髪が好き！太ももが好き！唇まで可愛い！
完全に真っ赤の顔でシャツをつかまえてるエマちゃんは最高です！
やばっ、可愛すぎてたまらん！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "あまね@Skeb*お仕事募集中"
handle = "amane0sleep"
twitter = "amane0sleep"
skeb = "amane0sleep"
pixiv = 230075