[request]
approved = 2021-12-06T22:41:43.688Z
completed = 2021-12-09T00:20:28.710Z
nsfw = false

body_english = """
ゆめみせなさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ゆめみせなさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごい！
差分が多くてすごすぎます！
全部はとても可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごい！
差分が多くてすごすぎます！
全部はとても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ゆめみ せな🍓🍼"
handle = "Sena_sweetmilk"
twitter = "Sena_sweetmilk"
skeb = "Sena_sweetmilk"
pixiv = 32523626