[request]
approved = 2021-10-18T02:51:34.775Z
completed = 2021-10-26T02:30:54.081Z
nsfw = false

body_english = """
沢木かれんさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
沢木かれんさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
エマちゃんとホットココ！
すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
エマちゃんとホットココ！
すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "沢木かれん.⋆✶"
handle = "karen1o27"
twitter = "karen1o27"
skeb = "karen1o27"
