[request]
approved = 2021-09-28T22:34:08.019Z
completed = 2021-10-08T11:10:26.188Z
nsfw = false

body_english = """
ヤマエさん、はじめまして！

実はリクエストしようと思っていましたので、アピールしてくれるのはすごく嬉しいです！

それで、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあったけど下のURLでは三面図を載せているツイートです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ヤマエさん、はじめまして！

実はリクエストしようと思っていましたので、アピールしてくれるのはすごく嬉しいです！

それで、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあったけど下のURLでは三面図を載せているツイートです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
エマちゃんの学校！
すごく可愛いです
ありがとうございます！
"""

boost_japanese = """
エマちゃんの学校！
すごく可愛いです
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ヤマエ@skeb募集中"
handle = "YamaGomasen"
twitter = "YamaGomasen"
skeb = "YamaGomasen"
pixiv = 4584582