[request]
approved = 2021-09-11T19:40:04.714Z
completed = 2021-09-22T18:52:33.619Z
nsfw = false

body_english = """
ぽえりむさん、はじめまして！

アピールしてありがとうございます！

ぽえりむさんのイラストはすごく可愛いです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細などお任せします！

そのツイートスレッドでもエマちゃんの私服を載せているツイートとエマちゃんの自己紹介がありますので、私服や他の衣装を描きたいなら、是非自由に描いて下さい！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ぽえりむさん、はじめまして！

アピールしてありがとうございます！

ぽえりむさんのイラストはすごく可愛いです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細などお任せします！

そのツイートスレッドでもエマちゃんの私服を載せているツイートとエマちゃんの自己紹介がありますので、私服や他の衣装を描きたいなら、是非自由に描いて下さい！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ぽえりむ♦️skeb受付中"
handle = "ooopppp4213_"
twitter = "ooopppp4213_"
skeb = "ooopppp4213_"
