[request]
approved = 2021-11-04T20:27:55.678Z
completed = 2021-11-07T08:41:22.142Z
nsfw = false

body_english = """
鳥村さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
鳥村さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "鳥村　skeb募集中"
handle = "torimuraa"
twitter = "torimuraa"
skeb = "torimuraa"
