[request]
approved = 2021-08-29T04:39:40.342Z
completed = 2021-09-08T06:25:40.493Z
nsfw = false

body_english = """
ゆーきゃん様、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ゆーきゃん様、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
衣装がめっちゃ好きです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
衣装がめっちゃ好きです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ゆーきゃん様"
handle = "you_can_prsk39"
twitter = "you_can_prsk39"
skeb = "you_can_prsk39"
