[request]
approved = 2021-07-21T04:13:15.759Z
completed = 2021-07-24T19:10:10.680Z
nsfw = false

body_english = """
塩八さん、こんにちは！

前回の甜花ちゃんのデフォルメ絵はすごく可愛かったので、今回は私のオリジナルキャラクターのエマちゃんのデフォルメ絵を描いてお願いしたいんです！

今回もまた個人観賞用のアクリルキーホルダーを作ってみたい！

下のURLでは三面図を載せているツイートです。

猫ちゃんと一緒を描くと嬉しいです。

他の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
塩八さん、こんにちは！

前回の甜花ちゃんのデフォルメ絵はすごく可愛かったので、今回は私のオリジナルキャラクターのエマちゃんのデフォルメ絵を描いてお願いしたいんです！

今回もまた個人観賞用のアクリルキーホルダーを作ってみたい！

下のURLでは三面図を載せているツイートです。

猫ちゃんと一緒を描くと嬉しいです。

他の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごい！
両面もめっちゃくちゃ可愛いです！
いつもありがとうございます！
"""

boost_japanese = """
わー！すごい！
両面もめっちゃくちゃ可愛いです！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "塩八❀Skeb・ご依頼受付中"
handle = "shiohachi"
twitter = "shiohachi"
skeb = "shiohachi"
pixiv = 15556886