[request]
approved = 2021-07-22T12:56:07.066Z
completed = 2021-08-04T12:19:44.793Z
nsfw = false

body_english = """
翠みや子さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです！

下のURLでは三面図を載せているツイートです。

エマちゃんはテニスのことがすごく大好きなので、テーマはテニスウエアを着て、ラケットを持って、写真のために可愛いポーズをしています！

他の詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
翠みや子さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです！

下のURLでは三面図を載せているツイートです。

エマちゃんはテニスのことがすごく大好きなので、テーマはテニスウエアを着て、ラケットを持って、写真のために可愛いポーズをしています！

他の詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉぉー！すごい！
テニスウエアですごく似合ってます！！
ありがとうございます！
"""

boost_japanese = """
うぉぉー！すごい！
テニスウエアですごく似合ってます！！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "翠みや子🌊Skeb受付中"
handle = "midor1_385"
twitter = "midor1_385"
skeb = "midor1_385"
pixiv = 3466301