[request]
approved = 2021-09-01T12:47:32.824Z
completed = 2021-09-18T13:28:54.958Z
nsfw = false

body_english = """
ぜろりくさん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです。

もうすでに知っていますが、新しい私服をデザインして貰いましたので、その私服を描いてくれると嬉しいです！

下のURLでは衣装の参考ツイートです！

イラストはエマちゃんを涼しくように足だけ水につけていて、夏の太陽を楽しんでいて、のんびりしています！

他の詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

body_japanese = """
ぜろりくさん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです。

もうすでに知っていますが、新しい私服をデザインして貰いましたので、その私服を描いてくれると嬉しいです！

下のURLでは衣装の参考ツイートです！

イラストはエマちゃんを涼しくように足だけ水につけていて、夏の太陽を楽しんでいて、のんびりしています！

他の詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

boost_english = """
うわぁー！すごい！
背景はめっちゃきれいです！
エマちゃんもすごく可愛いです！
いつもありがとうございます！
"""

boost_japanese = """
うわぁー！すごい！
背景はめっちゃきれいです！
エマちゃんもすごく可愛いです！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ぜろのりく☆作業中1件♪"
handle = "zeronoriku00"
twitter = "zeronoriku00"
skeb = "zeronoriku00"
pixiv = 65783552