[request]
approved = 2021-06-20T04:41:35.337Z
completed = 2021-06-24T08:28:37.947Z
nsfw = false

body_english = """
瀬谷ねこさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
瀬谷ねこさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
アイスも可愛くて美味しそうです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
アイスも可愛くて美味しそうです！
ありがとうございます！
"""


[payment]
amount = 15000
boost = 5000

[creator]
name = "瀬谷ねこ@イラスト垢🌸"
handle = "setani_"
twitter = "setani_"
pixiv = 851231