[request]
approved = 2021-09-30T14:50:20.752Z
completed = 2021-10-14T21:15:22.773Z
nsfw = false

body_english = """
菓色さん、こんにちは！

またお世話になります！

菓色さんがエマちゃんも素敵だと思っていたので、今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

健全な子なので、健全なリクエストです！

エマちゃんはテニスのが好きなので、スポーツ関係のようなシーンで描いてくれたら嬉しいです！

詳細などお任せします！

いつもありがとうございます！
"""

body_japanese = """
菓色さん、こんにちは！

またお世話になります！

菓色さんがエマちゃんも素敵だと思っていたので、今回は私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

健全な子なので、健全なリクエストです！

エマちゃんはテニスのが好きなので、スポーツ関係のようなシーンで描いてくれたら嬉しいです！

詳細などお任せします！

いつもありがとうございます！
"""

boost_english = """
うぉー！すごいです！
エマちゃんすごくカッコイイよ！！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごいです！
エマちゃんすごくカッコイイよ！！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "菓色（かしき）@Skeb"
handle = "kashiki_main"
twitter = "kashiki_main"
skeb = "kashiki_main"
pixiv = 26805741