[request]
approved = 2021-07-19T12:43:29.895Z
completed = 2021-07-30T14:22:48.047Z
nsfw = false

body_english = """
カエサルさん、こんにちは！

アピールしてありがとうございます！

そのアイデアはすごく良いと思いますので、ピザを食べている姿のエマちゃんを描いてお願いしたいんです！

詳細などお任せします。

ありがとうございます！
"""

body_japanese = """
カエサルさん、こんにちは！

アピールしてありがとうございます！

そのアイデアはすごく良いと思いますので、ピザを食べている姿のエマちゃんを描いてお願いしたいんです！

詳細などお任せします。

ありがとうございます！
"""

boost_english = """
わー、すごい！
ピザを食べているエマちゃんはとても幸せそうです！
ありがとうございます！
"""

boost_japanese = """
わー、すごい！
ピザを食べているエマちゃんはとても幸せそうです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "カエサル"
handle = "caesarcola"
twitter = "caesarcola"
skeb = "caesarcola"
pixiv = 1384745