[request]
approved = 2021-08-05T18:27:11.428Z
completed = 2021-08-18T12:13:52.453Z
nsfw = false

body_english = """
鬼塚ひろむさん、はじめまして！

数ヶ月前私にアピールしましたが、その時には自分のキャラをデザイン中なので、鬼塚さんをいつかリクエストしたい人リストに加えました。なので、すごく遅くなってすみませんですが、アピールしてありがとうございます！

それでもしよかったら、私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
鬼塚ひろむさん、はじめまして！

数ヶ月前私にアピールしましたが、その時には自分のキャラをデザイン中なので、鬼塚さんをいつかリクエストしたい人リストに加えました。なので、すごく遅くなってすみませんですが、アピールしてありがとうございます！

それでもしよかったら、私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです。

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "鬼塚ひろむ🦋"
handle = "telltellbouzuuu"
twitter = "telltellbouzuuu"
skeb = "telltellbouzuuu"
pixiv = 39807018