[request]
approved = 2021-07-30T13:40:53.345Z
completed = 2021-11-26T17:19:36.671Z
nsfw = false

body_english = """
柑柚さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
柑柚さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
暖かくしてください、エマちゃん！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
暖かくしてください、エマちゃん！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "かんゆくん"
handle = "Citron_82"
twitter = "Citron_82"
skeb = "Citron_82"
pixiv = 1182517