[request]
approved = 2021-12-01T16:12:03.900Z
completed = 2021-12-08T19:37:02.579Z
nsfw = false

body_english = """
ごりらっくまさん、はじめまして！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ごりらっくまさん、はじめまして！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！熊さんとウサギさんがいっぱい！
とても可愛いです！
衣装も素敵です！
ありがとうございます！
"""

boost_japanese = """
わー！熊さんとウサギさんがいっぱい！
とても可愛いです！
衣装も素敵です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ごりらっくま🔞skeb受付中"
handle = "gorillakkuman"
twitter = "gorillakkuman"
skeb = "gorillakkuman"
pixiv = 64023161