[request]
approved = 2021-10-29T14:40:41.014Z
completed = 2021-11-12T09:13:29.587Z
nsfw = false

body_english = """
にゅにゃさん、はじめまして！

アピールしてありがとうございます！

オリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
にゅにゃさん、はじめまして！

アピールしてありがとうございます！

オリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
真っ赤の顔とマフラー！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
真っ赤の顔とマフラー！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "にゅ•ω•*にゃ@🎨Skeb募集中‼️"
handle = "nyunya_38"
twitter = "nyunya_38"
skeb = "nyunya_38"
pixiv = 13299453