[request]
approved = 2021-10-01T02:05:47.764Z
completed = 2021-10-11T12:05:11.940Z
nsfw = false

body_english = """
蒼ウサギさん、こんにちは！

またお世話になります！

前回のエマちゃんはとても可愛かったので、また私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

衣装の間違えを気付いて教えてくれてありがとうございます！本当に何も言わなかったら私は全然気付いてないと思います！

今回はエマちゃんの私服を描いてくれるとすごく嬉しいです！

下のURLでは私服の参考ツイートです！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

body_japanese = """
蒼ウサギさん、こんにちは！

またお世話になります！

前回のエマちゃんはとても可愛かったので、また私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

衣装の間違えを気付いて教えてくれてありがとうございます！本当に何も言わなかったら私は全然気付いてないと思います！

今回はエマちゃんの私服を描いてくれるとすごく嬉しいです！

下のURLでは私服の参考ツイートです！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1432700549812703251
"""

boost_english = """
わー！まためっちゃ可愛いエマちゃんです！
本当にありがとうございます！
"""

boost_japanese = """
わー！まためっちゃ可愛いエマちゃんです！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "蒼ウサギ♂@skeb募集中"
handle = "AoUSA0328"
twitter = "AoUSA0328"
skeb = "AoUSA0328"
pixiv = 19095613