[request]
approved = 2021-06-20T06:39:19.796Z
completed = 2021-08-07T22:53:21.210Z
nsfw = false

body_english = """
んぬさん、こんにちは！

前回の甜花ちゃん依頼はめっちゃ可愛かったので、私のオリジナルキャラクターエマちゃんも描いてお願いしたいんです！

下のURLでは三面図を載せているツイートです！

今回はテーマなどお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
んぬさん、こんにちは！

前回の甜花ちゃん依頼はめっちゃ可愛かったので、私のオリジナルキャラクターエマちゃんも描いてお願いしたいんです！

下のURLでは三面図を載せているツイートです！

今回はテーマなどお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！猫耳エマちゃん！
めっちゃ可愛い！
ありがとうございます！
"""

boost_japanese = """
わー！猫耳エマちゃん！
めっちゃ可愛い！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "んぬ"
handle = "4nu15"
twitter = "4nu15"
skeb = "4nu15"
pixiv = 4103937