[request]
approved = 2021-07-16T13:56:48.480Z
completed = 2021-07-18T15:41:54.483Z
nsfw = false

body_english = """
音遠ういさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
音遠ういさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！猫ちゃんと遊んでる！
めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
うぉー！猫ちゃんと遊んでる！
めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "音遠うい"
handle = "u_i_nu"
twitter = "u_i_nu"
skeb = "u_i_nu"
