[request]
approved = 2021-07-30T14:02:52.230Z
completed = 2021-08-31T09:50:57.926Z
nsfw = false

body_english = """
やじさん、こんにちは！

またお世話になります。

エマちゃんの制服パーカーはとても可愛いですが、この暑い季節でパーカーを着てるのはちょっと暑すぎます！それで、もっと涼しい格好でお出かけしてるシーンが見てみたいと思います。

やじさんがデザインしたエマちゃんはとても可愛いなので、新しい衣装の詳細は全部やじさんにお任せします！

ありがとうございます！
"""

body_japanese = """
やじさん、こんにちは！

またお世話になります。

エマちゃんの制服パーカーはとても可愛いですが、この暑い季節でパーカーを着てるのはちょっと暑すぎます！それで、もっと涼しい格好でお出かけしてるシーンが見てみたいと思います。

やじさんがデザインしたエマちゃんはとても可愛いなので、新しい衣装の詳細は全部やじさんにお任せします！

ありがとうございます！
"""

boost_english = """
うわー！すごすぎます！
すごく夏っぽくて フレッシュな衣装です！
めっちゃ可愛いです！ありがとうございます！
"""

boost_japanese = """
うわー！すごすぎます！
すごく夏っぽくて フレッシュな衣装です！
めっちゃ可愛いです！ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "やじ"
handle = "YAZI114"
twitter = "YAZI114"
skeb = "YAZI114"
pixiv = 13748268