[request]
approved = 2021-12-27T21:27:29.374Z
completed = 2021-12-28T17:27:50.806Z
nsfw = false

body_english = """
朱院蒼紋はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので健全絵のリクエストだけど、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
朱院蒼紋はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので健全絵のリクエストだけど、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
えぇ！！少女エマの下剋上！！？
本好きの下剋上のカバーのパロディはすごく驚きました！笑笑
帯まで面白すぎる！
ありがとうございます！
"""

boost_japanese = """
えぇ！！少女エマの下剋上！！？
本好きの下剋上のカバーのパロディはすごく驚きました！笑笑
帯まで面白すぎる！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "朱院蒼紋 Skeb募集中"
handle = "akenoin"
twitter = "akenoin"
skeb = "akenoin"
pixiv = 3410