[request]
approved = 2021-06-28T03:15:06.808Z
completed = 2021-06-29T03:08:15.675Z
nsfw = false

body_english = """
由井ひな子さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
由井ひな子さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！めっちゃ可愛いです！
エマちゃんは猫ちゃんといちごを食べている！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃ可愛いです！
エマちゃんは猫ちゃんといちごを食べている！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "由井ひな子🐭"
handle = "yuihi_now"
twitter = "yuihi_now"
skeb = "yuihi_now"
