[request]
approved = 2021-12-07T14:02:15.728Z
completed = 2021-12-09T10:23:57.716Z
nsfw = false

body_english = """
フェルトさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えて嬉しいです！

もちろん、部屋着姿のエマちゃんを描いて頂きたいです！

もう見てなかったら、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
フェルトさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えて嬉しいです！

もちろん、部屋着姿のエマちゃんを描いて頂きたいです！

もう見てなかったら、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！めっちゃ可愛いです！
猫ちゃん達は可愛すぎます！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃ可愛いです！
猫ちゃん達は可愛すぎます！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "フェルト"
handle = "Felt_Kt"
twitter = "Felt_Kt"
skeb = "Felt_Kt"
