[request]
approved = 2021-09-30T20:41:49.464Z
completed = 2021-10-04T11:32:03.649Z
nsfw = false

body_english = """
ぷいさん、はじめまして！

アピールしてありがとうございます！

そうですよね！ツンデレでちっぱいは最高です！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあったけど下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ぷいさん、はじめまして！

アピールしてありがとうございます！

そうですよね！ツンデレでちっぱいは最高です！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあったけど下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！すごく可愛いです！
ぬいぐるみはとても素敵です！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごく可愛いです！
ぬいぐるみはとても素敵です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ぷ い"
handle = "RPuim1"
twitter = "RPuim1"
skeb = "RPuim1"
