[request]
approved = 2021-08-03T01:08:43.445Z
completed = 2021-09-19T10:05:40.405Z
nsfw = false

body_english = """
星野つむぎさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
星野つむぎさん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！可愛いです！
猫耳エマちゃんが世界一可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！可愛いです！
猫耳エマちゃんが世界一可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "星野"
handle = "mochipome514"
twitter = "mochipome514"
skeb = "mochipome514"
pixiv = 19524083