[request]
approved = 2021-11-03T12:34:40.492Z
completed = 2021-11-15T09:16:13.917Z
nsfw = false

body_english = """
ほしのさん、こんにちは！

またお世話になります！

今回もまたエマちゃんを描いて頂きたいです。

大体のテーマは猫耳としっぽを付けるエマちゃんです！

他の詳細などお任せします。

いつもありがとうございます！
"""

body_japanese = """
ほしのさん、こんにちは！

またお世話になります！

今回もまたエマちゃんを描いて頂きたいです。

大体のテーマは猫耳としっぽを付けるエマちゃんです！

他の詳細などお任せします。

いつもありがとうございます！
"""

boost_english = """
わー！相変わらずほしのさんの絵は素晴らしいです！
猫エマちゃんと2匹の猫ちゃんはとても可愛い！
いつもありがとうございます！
"""

boost_japanese = """
わー！相変わらずほしのさんの絵は素晴らしいです！
猫エマちゃんと2匹の猫ちゃんはとても可愛い！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "☆"
handle = "rst_hoshinono"
twitter = "rst_hoshinono"
skeb = "rst_hoshinono"
