[request]
approved = 2021-07-26T21:47:50.134Z
completed = 2021-09-01T13:49:25.900Z
nsfw = false

body_english = """
躬月さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
躬月さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！照れちゃったのに猫耳を本当に着てくれた！
めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！照れちゃったのに猫耳を本当に着てくれた！
めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "躬月(みつき)skeb募集中"
handle = "happy100012"
twitter = "happy100012"
skeb = "happy100012"
