[request]
approved = 2021-11-05T07:44:53.205Z
completed = 2021-11-07T12:34:37.964Z
nsfw = false

body_english = """
川上りらさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
川上りらさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "川上りら🌠コミッション募集中❗"
handle = "kawakamiLira"
twitter = "kawakamiLira"
skeb = "kawakamiLira"
