[request]
approved = 2021-06-01T12:41:32.286Z
completed = 2021-07-03T00:32:33.965Z
nsfw = false

body_english = """
ましまろさん、こんにちは！

またお世話になります！

今回は私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

シチュは学校のプールでスクール水着を着ています！

詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ましまろさん、こんにちは！

またお世話になります！

今回は私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

シチュは学校のプールでスクール水着を着ています！

詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
やっぱりエマちゃんはスク水を着てるのは最高です！
猫耳差分もすごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
やっぱりエマちゃんはスク水を着てるのは最高です！
猫耳差分もすごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ましまろのついったー"
handle = "msmrdaaaaa"
twitter = "msmrdaaaaa"
skeb = "msmrdaaaaa"
pixiv = 15867481