[request]
approved = 2021-09-29T07:59:35.650Z
completed = 2021-10-07T11:15:33.553Z
nsfw = false

body_english = """
和香奈さん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えて本当に嬉しいです！

沢山のすごく良い衣装のアイデアを教えてありがとうございます！

エマちゃんのような胸が小さいキャラがチャイナ服を着るとすごく好きなので、流石にエマちゃんもきっとチャイナ服が似合うと思います！

それで、チャイナ服のエマちゃんを描いたら嬉しいです！

下のURLではエマちゃんの三面図を載せているツイートです！

他の詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
和香奈さん、はじめまして！

アピールしてありがとうございます！

こんなの優しいメッセージを貰えて本当に嬉しいです！

沢山のすごく良い衣装のアイデアを教えてありがとうございます！

エマちゃんのような胸が小さいキャラがチャイナ服を着るとすごく好きなので、流石にエマちゃんもきっとチャイナ服が似合うと思います！

それで、チャイナ服のエマちゃんを描いたら嬉しいです！

下のURLではエマちゃんの三面図を載せているツイートです！

他の詳細などお任せします！

ありがとうございます！
"""

boost_english = """
わー！2つの衣装です！
両もすごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！2つの衣装です！
両もすごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "和香奈"
handle = "kmkwuzn0404"
twitter = "kmkwuzn0404"
skeb = "kmkwuzn0404"
pixiv = 2200289