[request]
approved = 2021-07-09T16:57:51.042Z
completed = 2021-07-16T22:44:36.072Z
nsfw = false

body_english = """
𝕔𝕙𝕣𝕠𝕟𝕚𝕔𝕒さん、はじめまして！

本当にお久しぶりですね！

またアピールしてありがとうございます！

今度は私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

夏っぽいの感じで描いてくれると嬉しいです。

詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
𝕔𝕙𝕣𝕠𝕟𝕚𝕔𝕒さん、はじめまして！

本当にお久しぶりですね！

またアピールしてありがとうございます！

今度は私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

夏っぽいの感じで描いてくれると嬉しいです。

詳細などお任せします。

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごい！
両の衣装はめっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごい！
両の衣装はめっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "𝕔𝕙𝕣𝕠𝕟𝕚𝕔𝕒"
handle = "chr0nica"
twitter = "chr0nica"
skeb = "chr0nica"
