[request]
approved = 2021-09-07T00:07:58.322Z
completed = 2021-09-14T19:13:12.610Z
nsfw = false

body_english = """
左原ツグミさん、はじめまして！

アピールしてありがとうございます！

もちろん、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図を載せているツイートです！

エプロンドレスを着ているエマちゃんはきっと似合いそうなので、是非描いてくれたら嬉しいです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
左原ツグミさん、はじめまして！

アピールしてありがとうございます！

もちろん、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです！

下のURLでは三面図を載せているツイートです！

エプロンドレスを着ているエマちゃんはきっと似合いそうなので、是非描いてくれたら嬉しいです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！2つの衣装！
両もすごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！2つの衣装！
両もすごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "左原ツグミ@Skeb募集中"
handle = "sahara_tsugumi"
twitter = "sahara_tsugumi"
skeb = "sahara_tsugumi"
