[request]
approved = 2021-10-07T16:53:34.991Z
completed = 2021-10-11T13:15:55.208Z
nsfw = false

body_english = """
きゅんもふさん、はじめまして！

アピールしてありがとうございます！

きゅんもふさんのめぐみイラストはとても可愛いです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
きゅんもふさん、はじめまして！

アピールしてありがとうございます！

きゅんもふさんのめぐみイラストはとても可愛いです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全絵のリクエストですけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉぉ！すごく可愛いです！
私服ですごく夏っぽいエマちゃんは最高です！
ありがとうございます！
"""

boost_japanese = """
うぉぉ！すごく可愛いです！
私服ですごく夏っぽいエマちゃんは最高です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "きゅんもふ✡️"
handle = "mofuumoff"
twitter = "mofuumoff"
skeb = "mofuumoff"
