[request]
approved = 2021-08-17T00:36:53.643Z
completed = 2021-08-17T00:38:48.841Z
nsfw = false

body_english = """
ゆうてけさん、こんにちは！

私のオリジナルキャラクター、エマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細はカフェの外のテーブルでエマちゃんがフラペ見たいな飲み物とケーキか他のデザートを持ってる。

他の席は空いているけど、デートっぽいな感じです。まるでイラストを見ている人がエマちゃんとデートしてるとテーブルに戻っています。

他の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ゆうてけさん、こんにちは！

私のオリジナルキャラクター、エマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細はカフェの外のテーブルでエマちゃんがフラペ見たいな飲み物とケーキか他のデザートを持ってる。

他の席は空いているけど、デートっぽいな感じです。まるでイラストを見ている人がエマちゃんとデートしてるとテーブルに戻っています。

他の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！めっちゃくちゃ可愛いです！
顔ですこし生クリームがあるのは可愛すぎる！
フラペとケーキもすごく美味そうです！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃくちゃ可愛いです！
顔ですこし生クリームがあるのは可愛すぎる！
フラペとケーキもすごく美味そうです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "綾風ゆうてけ"
handle = "yuteke_key"
twitter = "yuteke_key"
skeb = "yuteke_key"
pixiv = 13039894