[request]
approved = 2021-06-29T14:36:16.972Z
completed = 2021-07-02T05:03:26.723Z
nsfw = false

body_english = """
四葉はるさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
四葉はるさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！すごくきれいです！
エマちゃんはとても可愛いです！めっちゃ美人です！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごくきれいです！
エマちゃんはとても可愛いです！めっちゃ美人です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "四葉はる"
handle = "yotsuba_haru"
twitter = "yotsuba_haru"
skeb = "yotsuba_haru"
pixiv = 1748250