[request]
approved = 2021-08-05T22:08:19.218Z
completed = 2021-09-13T08:53:06.876Z
nsfw = false

body_english = """
ぴぴぴさん、はじめまして！

アピールしてありがとうございます！

こんなの長くて優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

実は最近、ちょっと雰囲気が暗いのアイデアを考えたのでこのタイミングはちょうど良かったです！こういう厚塗りの暗い雰囲気ですごく似合うと思っています！

高校の文化祭でエマちゃんのクラスが最恐のお化け屋敷を作ってみたかったので、エマちゃんは一番怖い幽霊になるために盛り上がっていました！それで、お化け屋敷で写真のために怖くて可愛いポーズにしています。

他の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ぴぴぴさん、はじめまして！

アピールしてありがとうございます！

こんなの長くて優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

実は最近、ちょっと雰囲気が暗いのアイデアを考えたのでこのタイミングはちょうど良かったです！こういう厚塗りの暗い雰囲気ですごく似合うと思っています！

高校の文化祭でエマちゃんのクラスが最恐のお化け屋敷を作ってみたかったので、エマちゃんは一番怖い幽霊になるために盛り上がっていました！それで、お化け屋敷で写真のために怖くて可愛いポーズにしています。

他の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごい！
怖そうなのにさすがに可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごい！
怖そうなのにさすがに可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ぴぴぴ"
handle = "pipipipikyomu"
twitter = "pipipipikyomu"
skeb = "pipipipikyomu"
