[request]
approved = 2021-11-13T10:11:30.882Z
completed = 2021-11-19T10:11:53.449Z
nsfw = false

body_english = """
pandaさん、はじめまして！

アピールしてありがとうございます！

オリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
pandaさん、はじめまして！

アピールしてありがとうございます！

オリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うぉー！すごいです！
こんなにエマちゃんの好きな物といます！！
すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
うぉー！すごいです！
こんなにエマちゃんの好きな物といます！！
すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "panda@3件作業中"
handle = "panda86980732"
twitter = "panda86980732"
skeb = "panda86980732"
