[request]
approved = 2021-10-04T17:22:24.667Z
completed = 2021-11-15T09:35:53.304Z
nsfw = false

body_english = """
やじさん、こんにちは！

またお世話になります！

今回は家でくつろいでいるエマちゃんを描いて頂きたいです。

家でくつろいでいる時に制服パーカーか前回の私服のはちょっとやりすぎるので、すごく可愛い部屋着描いてくれると嬉しいです！

詳細などお任せします！

いつもありがとうございます！
"""

body_japanese = """
やじさん、こんにちは！

またお世話になります！

今回は家でくつろいでいるエマちゃんを描いて頂きたいです。

家でくつろいでいる時に制服パーカーか前回の私服のはちょっとやりすぎるので、すごく可愛い部屋着描いてくれると嬉しいです！

詳細などお任せします！

いつもありがとうございます！
"""

boost_english = """
エマちゃんの部屋着！！！！
本当に本当に可愛いすぎる！
いつもありがとうございます！
"""

boost_japanese = """
エマちゃんの部屋着！！！！
本当に本当に可愛いすぎる！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "やじ"
handle = "YAZI114"
twitter = "YAZI114"
skeb = "YAZI114"
pixiv = 13748268