[request]
approved = 2021-06-24T09:33:03.850Z
completed = 2021-06-26T15:14:43.504Z
nsfw = false

body_english = """
馬場ケンタウロスさん、はじめまして！

アピールしてありがとうございます！

もしよかったら、私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

スク水を着ている姿を描いてくれると嬉しいです。

他の詳細などお任せします。

ありがとうございます！
"""

body_japanese = """
馬場ケンタウロスさん、はじめまして！

アピールしてありがとうございます！

もしよかったら、私のオリジナルキャラクターエマちゃんを描いてお願いしたいんです。

下のURLでは三面図を載せているツイートです！

スク水を着ている姿を描いてくれると嬉しいです。

他の詳細などお任せします。

ありがとうございます！
"""

boost_english = """
スク水は最高！
ありがとうございます！
"""

boost_japanese = """
スク水は最高！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "馬場ケンタウロス"
handle = "babaken12345"
twitter = "babaken12345"
pixiv = 69845386