[request]
approved = 2021-09-21T02:50:12.664Z
completed = 2021-09-28T18:16:17.284Z
nsfw = true

body_english = """
神門さん、はじめまして！

アピールしてありがとうございます！

アピールのメセージを誤解しているかもしれませんが、甜花ちゃんをリクエストしても良いですか？

最近はエマちゃんばっかりリクエストしていますので、もっと甜花ちゃんをリクエストしたいと思いますので、よかったら、「小女ラムネ」の「足立甜花」を描いて頂きたいです。

神門さんの足の絵はすごくエロいので、そういうのエロい甜花ちゃんを描いたらとても嬉しいです！

他の詳細などお任せします！

ありがとうございます！
"""

body_japanese = """
神門さん、はじめまして！

アピールしてありがとうございます！

アピールのメセージを誤解しているかもしれませんが、甜花ちゃんをリクエストしても良いですか？

最近はエマちゃんばっかりリクエストしていますので、もっと甜花ちゃんをリクエストしたいと思いますので、よかったら、「小女ラムネ」の「足立甜花」を描いて頂きたいです。

神門さんの足の絵はすごくエロいので、そういうのエロい甜花ちゃんを描いたらとても嬉しいです！

他の詳細などお任せします！

ありがとうございます！
"""

boost_english = """
うぉー！すごい！
めっちゃエロ可愛い！
ありがとうございます！
こんな沢山の差分もありがとうございます！
"""

boost_japanese = """
うぉー！すごい！
めっちゃエロ可愛い！
ありがとうございます！
こんな沢山の差分もありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "神門（かみもん）＠Skeb募集中"
handle = "SchwarzKap"
twitter = "SchwarzKap"
skeb = "SchwarzKap"
pixiv = 1437365