[request]
approved = 2022-04-11T02:11:36.762Z
completed = 2022-04-11T23:24:20.057Z
nsfw = false

body_english = """
花咲りねさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
花咲りねさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！めっちゃ可愛い！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃ可愛い！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "花咲りね🌷skeb受け付けてます"
handle = "ri9nee"
twitter = "ri9nee"
skeb = "ri9nee"
