[request]
approved = 2022-01-13T17:25:19.762Z
completed = 2022-01-19T00:30:05.275Z
nsfw = false

body_english = """
らみさん、こんにちは！

またお世話になります！

前回のエマちゃんはとても可愛かったし、また機会があったらメイドが描いてみたいって言われたので、今回はメイドエマちゃんを描いて頂きたいです！

詳細など全部お任せします！

いつも本当にありがとうございます！
"""

body_japanese = """
らみさん、こんにちは！

またお世話になります！

前回のエマちゃんはとても可愛かったし、また機会があったらメイドが描いてみたいって言われたので、今回はメイドエマちゃんを描いて頂きたいです！

詳細など全部お任せします！

いつも本当にありがとうございます！
"""

boost_english = """
えぇ！すごい！
メイドエマちゃんは流石に可愛すぎ！
猫耳とリボンで結んだ尻尾も素敵です！
いつもありがとうございます！
"""

boost_japanese = """
えぇ！すごい！
メイドエマちゃんは流石に可愛すぎ！
猫耳とリボンで結んだ尻尾も素敵です！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "らみ🍥"
handle = "Lamy_chun"
twitter = "Lamy_chun"
skeb = "Lamy_chun"
pixiv = 59462809