[request]
approved = 2022-04-14T23:02:29.497Z
completed = 2022-06-03T14:46:08.417Z
nsfw = false

body_english = """
秋葩さん、はじめまして！

アピールしてありがとうございます！

とても優しいメッセージを貰って嬉しいです！

エマちゃんの設定シートまで読んでくれてありがとうございました！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

エマちゃんはとても良い子なので健全のリクエストだけど、詳細など全部お任せします！

ありがとうございます！
"""

body_japanese = """
秋葩さん、はじめまして！

アピールしてありがとうございます！

とても優しいメッセージを貰って嬉しいです！

エマちゃんの設定シートまで読んでくれてありがとうございました！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

エマちゃんはとても良い子なので健全のリクエストだけど、詳細など全部お任せします！

ありがとうございます！
"""

boost_english = """
めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "秋葩🎀Skeb受付中！"
handle = "Akiha_3tsuki"
twitter = "Akiha_3tsuki"
skeb = "Akiha_3tsuki"
pixiv = 14381913