[request]
approved = 2022-02-28T01:29:51.058Z
completed = 2022-03-04T09:11:02.692Z
nsfw = false

body_english = """
みみっきゅさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細がなくてすみませんだけど、どんなエマちゃんでも描いてくれても嬉しいので、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
みみっきゅさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細がなくてすみませんだけど、どんなエマちゃんでも描いてくれても嬉しいので、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！とても可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！とても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "みみっきゅ🐰有償依頼受付中"
handle = "mimikyunosub"
twitter = "mimikyunosub"
skeb = "mimikyunosub"
pixiv = 58883037