[request]
approved = 2022-02-09T13:27:02.073Z
completed = 2022-02-14T13:57:03.369Z
nsfw = true

body_english = """
神門さん、こんにちは！

またお世話になります！

またエマちゃんを描いて頂きたいです！

今回はバレンタインイラスト描いてくれたら嬉しいです！

詳細など全部お任せします！

いつもありがとうございます！
"""

body_japanese = """
神門さん、こんにちは！

またお世話になります！

またエマちゃんを描いて頂きたいです！

今回はバレンタインイラスト描いてくれたら嬉しいです！

詳細など全部お任せします！

いつもありがとうございます！
"""

boost_english = """
わー！いつものように素敵です！
ありがとうございます！
"""

boost_japanese = """
わー！いつものように素敵です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "神門（かみもん）@Skeb募集中"
handle = "SchwarzKap"
twitter = "SchwarzKap"
skeb = "SchwarzKap"
pixiv = 1437365