[request]
approved = 2022-01-02T22:32:02.436Z
completed = 2022-01-15T22:30:32.022Z
nsfw = false

body_english = """
クズミクルスさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
クズミクルスさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わぁ～！可愛すぎ！
やはりエマちゃんも女の子らしい服を買いたいね！
ありがとうございます！
"""

boost_japanese = """
わぁ～！可愛すぎ！
やはりエマちゃんも女の子らしい服を買いたいね！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "クズミクルス／来栖久住"
handle = "kuzumicruz"
twitter = "kuzumicruz"
skeb = "kuzumicruz"
