[request]
approved = 2022-01-24T03:41:02.369Z
completed = 2022-04-03T14:29:36.545Z
nsfw = false

body_english = """
RIKAさん、はじめまして！

すごく遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです。

エマちゃんはとても良い子なので健全のリクエストだし、あまり詳細がなくてもすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいので、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
RIKAさん、はじめまして！

すごく遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです。

エマちゃんはとても良い子なので健全のリクエストだし、あまり詳細がなくてもすみませんだけど、どんな可愛いエマちゃんを描いてくれたら嬉しいので、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
可愛いです！
ありがとうございます！
"""

boost_japanese = """
可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "RIKA@Skeb募集中…((꜆˙꒳˙)꜆"
handle = "yuukazomi"
twitter = "yuukazomi"
skeb = "yuukazomi"
pixiv = 9859327