[request]
approved = 2022-04-13T03:40:43.007Z
completed = 2022-04-17T16:12:05.310Z
nsfw = false

body_english = """
神門さん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです！

イースターは近いので、イースターのイラスト描いてくれたら嬉しいです！

詳細など全部お任せします！

いつもありがとうございます！
"""

body_japanese = """
神門さん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです！

イースターは近いので、イースターのイラスト描いてくれたら嬉しいです！

詳細など全部お任せします！

いつもありがとうございます！
"""

boost_english = """
あぁ！とても素敵です！
いつもありがとうございます！
"""

boost_japanese = """
あぁ！とても素敵です！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "神門（かみもん）@Skeb募集中"
handle = "SchwarzKap"
twitter = "SchwarzKap"
skeb = "SchwarzKap"
pixiv = 1437365