[request]
approved = 2021-12-07T04:40:33.540Z
completed = 2022-02-04T14:51:58.610Z
nsfw = false

body_english = """
ぜろりくさん、こんにちは！

またエマちゃんを描いて頂きたいだけど、よかったら今回は詳細を全部お任せします！

どのようなエマちゃんを描くのがすごく楽しみにしています！

いつも本当にありがとうございます！
"""

body_japanese = """
ぜろりくさん、こんにちは！

またエマちゃんを描いて頂きたいだけど、よかったら今回は詳細を全部お任せします！

どのようなエマちゃんを描くのがすごく楽しみにしています！

いつも本当にありがとうございます！
"""

boost_english = """
わー！本当に最高です！
今までのリクエストは本当に素晴らしいなのに、これはなんとすごすぎます！
本当にいつもありがとうございます！泣いちゃうよ！😭
"""

boost_japanese = """
わー！本当に最高です！
今までのリクエストは本当に素晴らしいなのに、これはなんとすごすぎます！
本当にいつもありがとうございます！泣いちゃうよ！😭
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ぜろのりく"
handle = "zeronoriku00"
twitter = "zeronoriku00"
skeb = "zeronoriku00"
pixiv = 65783552