[request]
approved = 2022-05-18T22:57:50.084Z
completed = 2022-06-06T02:38:02.072Z
nsfw = false

body_english = """
やみなべさん、はじめまして！

大変遅くなってすみませんですがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
やみなべさん、はじめまして！

大変遅くなってすみませんですがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わ！めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わ！めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "やみなべ"
handle = "szhal14"
twitter = "szhal14"
skeb = "szhal14"
pixiv = 25896009