[request]
approved = 2022-04-28T09:57:31.681Z
completed = 2022-05-02T08:31:05.378Z
nsfw = false

body_english = """
ちさくさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ちさくさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！苺の衣装だ！可愛い！
ありがとうございます！
"""

boost_japanese = """
わー！苺の衣装だ！可愛い！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "⛏️ちさく🕶"
handle = "nhb_265"
twitter = "nhb_265"
skeb = "nhb_265"
