[request]
approved = 2022-05-18T14:55:03.877Z
completed = 2022-07-08T09:39:56.516Z
nsfw = false

body_english = """
湊ゆうさん、はじめまして！

大変遅くなってすみませんですがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
湊ゆうさん、はじめまして！

大変遅くなってすみませんですがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わぁ！めっちゃ可愛いです！
とっても素敵なシーンだ、、、
本当にありがとうございます！
"""

boost_japanese = """
わぁ！めっちゃ可愛いです！
とっても素敵なシーンだ、、、
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "湊ゆう"
handle = "minato_yu34"
twitter = "minato_yu34"
skeb = "minato_yu34"
