[request]
approved = 2022-04-28T03:01:35.103Z
completed = 2022-05-07T13:43:30.680Z
nsfw = false

body_english = """
川上らいとさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
川上らいとさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
すごく可愛いです！！
パフェもめっちゃ美味しそう！
ありがとうございます！
"""

boost_japanese = """
すごく可愛いです！！
パフェもめっちゃ美味しそう！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "川上らいと@skeb受付中"
handle = "raraRaITo1013"
twitter = "raraRaITo1013"
skeb = "raraRaITo1013"
pixiv = 2598839