[request]
approved = 2022-07-15T03:04:19.309Z
completed = 2022-07-29T09:46:32.843Z
nsfw = true

body_english = """
神門さん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです！

最近はとても暑いので、エマちゃんのセーラーワンピースを描いてくれたら嬉しいです！

詳細など全部お任せします！

いつもありがとうございます！
"""

body_japanese = """
神門さん、こんにちは！

またお世話になります！

今回もエマちゃんを描いて頂きたいです！

最近はとても暑いので、エマちゃんのセーラーワンピースを描いてくれたら嬉しいです！

詳細など全部お任せします！

いつもありがとうございます！
"""

boost_english = """
すごく素敵です！
いつもありがとうございます！
"""

boost_japanese = """
すごく素敵です！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "神門（かみもん）"
handle = "SchwarzKap"
twitter = "SchwarzKap"
skeb = "SchwarzKap"
pixiv = 1437365