[request]
approved = 2022-04-15T14:25:46.673Z
completed = 2022-04-17T10:21:02.615Z
nsfw = false

body_english = """
かぶたぬこさん、はじめまして！

アピールしてありがとうございます！

設定シートまで読んでくれてありがとうございました！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

エマちゃんはとても良い子なので健全のリクエストだけど、詳細など全部お任せします！

ありがとうございます！
"""

body_japanese = """
かぶたぬこさん、はじめまして！

アピールしてありがとうございます！

設定シートまで読んでくれてありがとうございました！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

エマちゃんはとても良い子なので健全のリクエストだけど、詳細など全部お任せします！

ありがとうございます！
"""

boost_english = """
わー！めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "かぶたぬこ"
handle = "nyanpukutei"
twitter = "nyanpukutei"
skeb = "nyanpukutei"
pixiv = 3852468