[request]
approved = 2022-01-27T13:15:14.059Z
completed = 2022-03-17T13:01:14.916Z
nsfw = false

body_english = """
ドリアーヌさん、はじめまして！

アピールしてありがとうございます！

こんな優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので健全のリクエストだけど、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ドリアーヌさん、はじめまして！

アピールしてありがとうございます！

こんな優しいメッセージを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので健全のリクエストだけど、詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わ～！めっちゃ可愛いです！
髪が特に大好きです！
ありがとうございます！
"""

boost_japanese = """
わ～！めっちゃ可愛いです！
髪が特に大好きです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ドリアーヌ🔞skeb募集中！！"
handle = "DORIANE_DOJIN"
twitter = "DORIANE_DOJIN"
skeb = "DORIANE_DOJIN"
pixiv = 28987176