[request]
approved = 2022-02-08T07:42:03.556Z
completed = 2022-02-14T06:50:06.742Z
nsfw = false

body_english = """
水無月美桜さん、はじめまして！

またお世話になります！

今回もエマちゃんを描いて頂きたいです。

大体のテーマはバレンタインデーなので、個人的に見たいのラブラブエマちゃんを自由に描いて下さい！

詳細などお任せします！

いつもありがとうございます！
"""

body_japanese = """
水無月美桜さん、はじめまして！

またお世話になります！

今回もエマちゃんを描いて頂きたいです。

大体のテーマはバレンタインデーなので、個人的に見たいのラブラブエマちゃんを自由に描いて下さい！

詳細などお任せします！

いつもありがとうございます！
"""

boost_english = """
わー！とても可愛いです！
エマちゃんとチョコもすごく美味しそうです！
ミニキャラも素敵です！
いつもありがとうございます！
"""

boost_japanese = """
わー！とても可愛いです！
エマちゃんとチョコもすごく美味しそうです！
ミニキャラも素敵です！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "水無月 美桜🌸"
handle = "MINAZUKI_MIOU"
twitter = "MINAZUKI_MIOU"
skeb = "MINAZUKI_MIOU"
pixiv = 31293558