[request]
approved = 2022-05-20T16:05:39.643Z
completed = 2022-05-23T03:57:15.430Z
nsfw = false

body_english = """
なかさごさん、こんにちは！

またお世話になります！

前回のエマちゃんはめっちゃ可愛かったので、今回はエマちゃんの私服を描いて頂きたいです！

詳細など全部お任せします！

いつも本当にありがとうございます！
"""

body_japanese = """
なかさごさん、こんにちは！

またお世話になります！

前回のエマちゃんはめっちゃ可愛かったので、今回はエマちゃんの私服を描いて頂きたいです！

詳細など全部お任せします！

いつも本当にありがとうございます！
"""

boost_english = """
わぁ！また大変可愛いツンデレエマちゃんだ！
本当に大好きです！
ありがとうございます！
"""

boost_japanese = """
わぁ！また大変可愛いツンデレエマちゃんだ！
本当に大好きです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "なかさご"
handle = "Nakasago35"
twitter = "Nakasago35"
skeb = "Nakasago35"
pixiv = 5006883