[request]
approved = 2022-05-01T05:50:04.767Z
completed = 2022-05-13T10:11:41.428Z
nsfw = false

body_english = """
おうみやひなりさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
おうみやひなりさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
とても可愛いです！
ありがとうございます！
"""

boost_japanese = """
とても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "おうみやひなり"
handle = "oumiyahinari"
twitter = "oumiyahinari"
skeb = "oumiyahinari"
pixiv = 107313