[request]
approved = 2022-08-02T15:17:30.563Z
completed = 2022-08-04T02:56:28.582Z
nsfw = false

body_english = """
なかさごさん、こんにちは！

またお世話になります！

今回もまたエマちゃんを描いて頂きたいです！

この度は巫女服を着てるエマちゃんを描いてくれたら嬉しいです！

他の詳細など全部お任せします！

いつもありがとうございます！
"""

body_japanese = """
なかさごさん、こんにちは！

またお世話になります！

今回もまたエマちゃんを描いて頂きたいです！

この度は巫女服を着てるエマちゃんを描いてくれたら嬉しいです！

他の詳細など全部お任せします！

いつもありがとうございます！
"""

boost_english = """
早っ！とっても可愛いの巫女エマちゃんだ！
いつも本当にありがとうございます！
"""

boost_japanese = """
早っ！とっても可愛いの巫女エマちゃんだ！
いつも本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "なかさご@8/27誕生日デーーーース！！！！"
handle = "Nakasago35"
twitter = "Nakasago35"
skeb = "Nakasago35"
pixiv = 5006883