[request]
approved = 2022-03-26T18:18:13.861Z
completed = 2022-05-12T04:59:46.964Z
nsfw = false

body_english = """
あまみねさん、はじめまして！

カナダからの大ファンです！

もし良かったら、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
あまみねさん、はじめまして！

カナダからの大ファンです！

もし良かったら、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
えぇ！！マジ可愛すぎ！
ずっと大切にします！
本当に本当にありがとうございます！
"""

boost_japanese = """
えぇ！！マジ可愛すぎ！
ずっと大切にします！
本当に本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "あまみね🌸新刊出ました"
handle = "amamine"
twitter = "amamine"
skeb = "amamine"
pixiv = 183606