[request]
approved = 2021-12-10T21:33:34.948Z
completed = 2022-02-06T13:34:36.016Z
nsfw = false

body_english = """
モティさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
モティさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです。

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
ミニキャラまでも描いてくれて嬉しいです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ミニキャラまでも描いてくれて嬉しいです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "わらび餅なモティ"
handle = "yuki39247652"
twitter = "moty_wm"
skeb = "yuki39247652"
pixiv = 46815637