[request]
approved = 2022-02-20T22:30:28.786Z
completed = 2022-04-04T16:19:53.113Z
nsfw = false

body_english = """
きなこさん、はじめまして！

アピールしてありがとうございます！

すごく優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
きなこさん、はじめまして！

アピールしてありがとうございます！

すごく優しいメッセージを貰えてとても嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "きなこ○お仕事.Skeb募集中"
handle = "Kinak0_mitu"
twitter = "Kinak0_mitu"
skeb = "Kinak0_mitu"
