[request]
approved = 2022-02-05T02:36:35.275Z
completed = 2022-04-04T12:32:19.543Z
nsfw = false

body_english = """
川上りらさん、こんにちは！

またお世話になります！

もし良かったら、またエマちゃんを描いて頂きたいです！

今回はエマちゃんの私服か部屋着を描いてくれたら嬉しいです！

どっちの衣装でも嬉しいので、衣装と詳細などお任せします！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
川上りらさん、こんにちは！

またお世話になります！

もし良かったら、またエマちゃんを描いて頂きたいです！

今回はエマちゃんの私服か部屋着を描いてくれたら嬉しいです！

どっちの衣装でも嬉しいので、衣装と詳細などお任せします！

いつもありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
すごくかわいいです！
もう一度ありがとうございます！
"""

boost_japanese = """
すごくかわいいです！
もう一度ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "川上りら🌠活動休止"
handle = "kawakamiLira"
twitter = "kawakamiLira"
skeb = "kawakamiLira"
