[request]
approved = 2022-04-01T07:43:31.415Z
completed = 2022-06-05T10:27:55.976Z
nsfw = false

body_english = """
やじさん、こんにちは！

またお世話になります！

今回はエマちゃんの誕生日のためにまたエマちゃんを描いて頂きたいです！

詳細など全部お任せします！

いつも本当にありがとうございます！
"""

body_japanese = """
やじさん、こんにちは！

またお世話になります！

今回はエマちゃんの誕生日のためにまたエマちゃんを描いて頂きたいです！

詳細など全部お任せします！

いつも本当にありがとうございます！
"""

boost_english = """
天使ですか！？
いつものようにマジ可愛すぎる！
本当にありがとうございます！
"""

boost_japanese = """
天使ですか！？
いつものようにマジ可愛すぎる！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "やじ"
handle = "YAZI114"
twitter = "YAZI114"
skeb = "YAZI114"
pixiv = 13748268