[request]
approved = 2022-01-13T20:52:25.520Z
completed = 2022-03-14T15:46:36.116Z
nsfw = false

body_english = """
あまやさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
あまやさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
すごく可愛いです！
ありがとうございます！
"""

boost_japanese = """
すごく可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "❄あまや❄"
handle = "amaya_kiku_"
twitter = "amaya_kiku_"
skeb = "amaya_kiku_"
pixiv = 16915497