[request]
approved = 2022-05-18T15:15:29.133Z
completed = 2022-06-06T09:07:02.929Z
nsfw = false

body_english = """
中山ゆきさん、はじめまして！

大変遅くなってすみませんですがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
中山ゆきさん、はじめまして！

大変遅くなってすみませんですがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
とても可愛いです！
ありがとうございます！
"""

boost_japanese = """
とても可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "中山 ゆき🍼マンガ家"
handle = "yukiyuki_nkym"
twitter = "yukiyuki_nkym"
skeb = "yukiyuki_nkym"
