[request]
approved = 2022-04-04T12:25:10.464Z
completed = 2022-04-24T06:45:36.472Z
nsfw = false

body_english = """
プリンプリンさん、はじめまして！

アピールしてありがとうございます！

こんなすごい絵師さんからアピールを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
プリンプリンさん、はじめまして！

アピールしてありがとうございます！

こんなすごい絵師さんからアピールを貰えてすごく嬉しいです！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
めっちゃ可愛い！
どこまで見ても好きすぎ！
本当にありがとうございます！
"""

boost_japanese = """
めっちゃ可愛い！
どこまで見ても好きすぎ！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "プリンプリン🍮"
handle = "prn0112"
twitter = "prn0112"
skeb = "prn0112"
pixiv = 4179