[request]
approved = 2022-01-05T06:30:04.765Z
completed = 2022-01-16T18:18:37.525Z
nsfw = false

body_english = """
るなちあさん、はじめまして！

るなちあさんの絵柄がすごく可愛いと思います！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので健全のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
るなちあさん、はじめまして！

るなちあさんの絵柄がすごく可愛いと思います！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはとても良い子なので健全のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わぁー！すごすぎます！
部屋着は本当に最高です…
ありがとうございます！
"""

boost_japanese = """
わぁー！すごすぎます！
部屋着は本当に最高です…
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "るなちあ"
handle = "runachia_s"
twitter = "runachia_s"
skeb = "runachia_s"
pixiv = 76861243