[request]
approved = 2021-12-05T16:55:16.453Z
completed = 2022-02-14T11:58:13.652Z
nsfw = false

body_english = """
やじさん、こんにちは！

またお世話になります！

今回はおしゃれの冬っぽいエマちゃんを描いて頂きたいです！

衣装の詳細など全部お任せします！

いつも本当にありがとうございます！
"""

body_japanese = """
やじさん、こんにちは！

またお世話になります！

今回はおしゃれの冬っぽいエマちゃんを描いて頂きたいです！

衣装の詳細など全部お任せします！

いつも本当にありがとうございます！
"""

boost_english = """
いつものようにとても素敵です！
本当にいろいろありがとうございます！
"""

boost_japanese = """
いつものようにとても素敵です！
本当にいろいろありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "やじ"
handle = "YAZI114"
twitter = "YAZI114"
skeb = "YAZI114"
pixiv = 13748268