[request]
approved = 2022-01-05T16:49:07.368Z
completed = 2022-01-09T11:10:35.304Z
nsfw = false

body_english = """
神﨑陸さん、はじめまして！

メスガキママの澪那ちゃんの大ファンです！

よかったら、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはツンデレなのでツンデレっぽいの感じで描いてくれたら嬉しいだけど、大体の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
神﨑陸さん、はじめまして！

メスガキママの澪那ちゃんの大ファンです！

よかったら、私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

エマちゃんはツンデレなのでツンデレっぽいの感じで描いてくれたら嬉しいだけど、大体の詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
うわぁ！最高です！
エマちゃんがその表情をしてるのはすごすぎ！
ありがとうございます！
"""

boost_japanese = """
うわぁ！最高です！
エマちゃんがその表情をしてるのはすごすぎ！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "神﨑 陸@新アカ移行中"
handle = "___RIC___"
twitter = "__RlC__"
skeb = "___RIC___"
pixiv = 22370158