[request]
approved = 2022-02-13T04:45:20.427Z
completed = 2022-02-18T06:57:50.374Z
nsfw = false

body_english = """
ukishizumiさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
ukishizumiさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
えぇ！めっちゃ可愛いです！
この表情は最高です！
ありがとうございます！
"""

boost_japanese = """
えぇ！めっちゃ可愛いです！
この表情は最高です！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ukishizumi"
handle = "_ukszm"
twitter = "_ukszm"
skeb = "_ukszm"
pixiv = 45559539