[request]
approved = 2022-03-05T00:46:45.997Z
completed = 2022-03-07T22:42:44.534Z
nsfw = false

body_english = """
琴かさん、はじめまして！

遅くなってすみませんがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
琴かさん、はじめまして！

遅くなってすみませんがアピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
えぇ！可愛すぎ！
猫ちゃんと桜を見てるのは楽しそう～！
ありがとうございます！
"""

boost_japanese = """
えぇ！可愛すぎ！
猫ちゃんと桜を見てるのは楽しそう～！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "琴か"
handle = "libre1907"
twitter = "libre1907"
skeb = "libre1907"
pixiv = 25349931