[request]
approved = 2021-12-06T01:01:11.930Z
completed = 2022-01-01T13:50:06.795Z
nsfw = false

body_english = """
めらみさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
めらみさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

もう見たことがあるけど、下のURLでは三面図を載せているツイートです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！エマちゃんの部屋！
可愛いすぎ！
ありがとうございます！
"""

boost_japanese = """
わー！エマちゃんの部屋！
可愛いすぎ！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "めらみ🎨Skebリクエスト受付中"
handle = "mmmera827"
twitter = "mmmera827"
skeb = "mmmera827"
pixiv = 62819125