[request]
approved = 2021-11-07T16:04:24.730Z
completed = 2022-01-21T09:04:43.843Z
nsfw = false

body_english = """
Reflaさん、はじめまして！

アピールしてありがとうございます！

エマちゃんにフリルいっぱいの可愛いお洋服はきっとすごく可愛いですね！描いて頂きたいです。

詳細などお任せします！

下のURLではエマちゃんの三面図を載せているツイートです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
Reflaさん、はじめまして！

アピールしてありがとうございます！

エマちゃんにフリルいっぱいの可愛いお洋服はきっとすごく可愛いですね！描いて頂きたいです。

詳細などお任せします！

下のURLではエマちゃんの三面図を載せているツイートです！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わ～！すごいです！
猫耳エマちゃんはいつもすごく可愛いけど、この衣装は本当にすごすぎます！
ありがとうございます！
"""

boost_japanese = """
わ～！すごいです！
猫耳エマちゃんはいつもすごく可愛いけど、この衣装は本当にすごすぎます！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "𝖱𝖾𝖿𝗅𝖺🌟依頼受付中"
handle = "refla_"
twitter = "refla_"
skeb = "refla_"
pixiv = 70088971