[request]
approved = 2022-04-28T02:21:17.141Z
completed = 2022-05-10T04:41:34.176Z
nsfw = false

body_english = """
井ノ内さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
井ノ内さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わーー！！とても綺麗です！
めっちゃ好きです！
ありがとうございます！
"""

boost_japanese = """
わーー！！とても綺麗です！
めっちゃ好きです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "井ノ内@skeb"
handle = "inocheese"
twitter = "inocheese"
skeb = "inocheese"
