[request]
approved = 2022-01-03T01:14:09.424Z
completed = 2022-02-05T05:10:53.152Z
nsfw = false

body_english = """
彩木ゆずりさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
彩木ゆずりさん、はじめまして！

ちょっと遅くなってすみませんけど、アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

エマちゃんはとても良い子なので健全のリクエストだけど、詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！可愛いです！
少しパンチラも見えて嬉しいです！
ありがとうございます！
"""

boost_japanese = """
わー！可愛いです！
少しパンチラも見えて嬉しいです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "彩木ゆずり@商業連載中"
handle = "itmnmi_d"
twitter = "itmnmi_d"
skeb = "itmnmi_d"
pixiv = 55994754