[request]
approved = 2022-04-01T15:13:56.351Z
completed = 2022-04-02T13:51:26.546Z
nsfw = false

body_english = """
いなみさん、こんにちは！お久しぶりですね！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
いなみさん、こんにちは！お久しぶりですね！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図を載せているツイートです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！とても可愛いです！
衣装２枚も描いてくれた！
本当にありがとうございます！
"""

boost_japanese = """
わー！とても可愛いです！
衣装２枚も描いてくれた！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "いなみ｜SD用サブ"
handle = "i7min_"
twitter = "i7min_"
skeb = "i7min_"
