[request]
approved = 2022-01-29T03:10:48.152Z
completed = 2022-01-31T13:51:18.112Z
nsfw = false

body_english = """
うぐさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
うぐさん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細などお任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わー！めっちゃ可愛いです！
ありがとうございます！
"""

boost_japanese = """
わー！めっちゃ可愛いです！
ありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "ugu"
handle = "fenganss"
twitter = "fenganss"
skeb = "fenganss"
pixiv = 13239483