[request]
approved = 2022-04-25T03:47:25.994Z
completed = 2022-06-11T08:47:52.269Z
nsfw = false

body_english = """
megapon98さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

body_japanese = """
megapon98さん、はじめまして！

アピールしてありがとうございます！

私のオリジナルキャラクターのエマちゃんを描いて頂きたいです。

下のURLでは三面図と設定シートと他の衣装を載せているツイートスレッドです！

詳細など全部お任せします！

ありがとうございます！

https://twitter.com/kazakuri/status/1397562595662512130
"""

boost_english = """
わぁ！めっちゃ可愛いです！
差分ととても優しいメッセージもありがとうございます！
本当にありがとうございます！
"""

boost_japanese = """
わぁ！めっちゃ可愛いです！
差分ととても優しいメッセージもありがとうございます！
本当にありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "megapon98❄️"
handle = "megapon98"
twitter = "megapon98"
skeb = "megapon98"
pixiv = 930959