[request]
approved = 2022-02-06T06:26:17.434Z
completed = 2022-04-27T07:11:45.593Z
nsfw = false

body_english = """
あまねさん、こんにちは！

またお世話になります！

今回はエマちゃんとあまねさんのうちの子のクロスオーバー絵を描いて頂きたいです！

詳細など全部お任せします。

いつもありがとうございます！
"""

body_japanese = """
あまねさん、こんにちは！

またお世話になります！

今回はエマちゃんとあまねさんのうちの子のクロスオーバー絵を描いて頂きたいです！

詳細など全部お任せします。

いつもありがとうございます！
"""

boost_english = """
とても素敵です！
めっちゃエマちゃんらしい！
いつもありがとうございます！
"""

boost_japanese = """
とても素敵です！
めっちゃエマちゃんらしい！
いつもありがとうございます！
"""


[payment]
amount = 0
boost = 0

[creator]
name = "あまね@Skeb*お仕事募集中"
handle = "amane0sleep"
twitter = "amane0sleep"
skeb = "amane0sleep"
pixiv = 230075