name: commission.tenka.dev
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Restore LFS cache
        uses: actions/cache@v2
        with:
          path: .git/lfs
          key: lfs-asset-cache-v1

      - name: Git LFS pull
        run: git lfs pull

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run Rust app
        uses: actions-rs/cargo@v1
        with:
          command: run 
          args: --release

      - name: Install and Run Zola
        run: |
          sudo snap install --edge zola
          zola build

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
