name: commission.tenka.dev
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: CI

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout
        uses: actions/checkout@master
      
      - name: Restore LFS cache
        uses: actions/cache@v2
        with:
          path: .git/lfs
          key: lfs-asset-cache-v2

      - name: Git LFS pull
        run: git lfs pull

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
          
      - name: Print failures 
        if: ${{ failure() }}
        run: git status

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run Rust Generate app
        uses: actions-rs/cargo@v1
        with:
          command: run 
          args: --release --bin generate

      - name: Run Rust Banner app
        uses: actions-rs/cargo@v1
        with:
          command: run 
          args: --release --bin banner

      - name: Run Rust Stats app
        uses: actions-rs/cargo@v1
        with:
          command: run 
          args: --release --bin stats

      - name: Run Rust Clean
        uses: actions-rs/cargo@v1
        with:
          command: clean

      - name: Install and Run Zola
        run: |
          sudo snap install --edge zola
          zola build

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
